export enum ErrorCode {
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  EXAM_NOT_FOUND = 'EXAM_NOT_FOUND',
  EXAM_ALREADY_SUBMITTED = 'EXAM_ALREADY_SUBMITTED',
  EXAM_QUESTION_NOT_FOUND = 'EXAM_QUESTION_NOT_FOUND',
  EXAM_INSUFFICIENT_QUESTIONS = 'EXAM_INSUFFICIENT_QUESTIONS',

  // Classroom
  CLASSROOM_NOT_FOUND = 'CLASSROOM_NOT_FOUND',
  CLASSROOM_ALREADY_JOINED = 'CLASSROOM_ALREADY_JOINED',
  CLASSROOM_INVALID_CODE = 'CLASSROOM_INVALID_CODE',
  CLASSROOM_NOT_MEMBER = 'CLASSROOM_NOT_MEMBER',

  // ExamSet
  EXAM_SET_NOT_FOUND = 'EXAM_SET_NOT_FOUND',
  EXAM_SET_EMPTY = 'EXAM_SET_EMPTY',

  // Feature flags
  FEATURE_DISABLED = 'FEATURE_DISABLED',

  // Assignment
  ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_EXPIRED = 'ASSIGNMENT_EXPIRED',
  ASSIGNMENT_ALREADY_SUBMITTED = 'ASSIGNMENT_ALREADY_SUBMITTED',
}

export class AppError extends Error {
  constructor(
    public message: string,
    public code: ErrorCode,
    public statusCode: number = 400,
    public details?: any
  ) {
    super(message);
    this.name = 'AppError';
  }
}
