-- AlterTable
ALTER TABLE "exam_sets" ADD COLUMN     "pointPerMC" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD COLUMN     "pointPerSA" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "pointPerTFItem" DOUBLE PRECISION NOT NULL DEFAULT 0.25;
