import { neon } from '@neondatabase/serverless';
import { randomUUID } from 'crypto';
import dotenv from 'dotenv';
dotenv.config();

const TEACHER_ID = 'b41b93bee9ed46f7ae09fc68a0c71e2c';

interface Q {
  content: string;
  topic: string;
  difficulty: string;
  format: string;
  options: string;
  answer: string;
  explanation: string;
  statementA?: string;
  statementB?: string;
  statementC?: string;
  statementD?: string;
  answerA?: boolean;
  answerB?: boolean;
  answerC?: boolean;
  answerD?: boolean;
  correctAnswer?: string;
}

// ============================================================
// TOPIC 1: DERIVATIVES (Đạo hàm) — 18 câu
// ============================================================
const derivativesQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Tính đạo hàm của hàm số $y = x^4 - 3x^2 + 5x - 7$.',
    topic: 'DERIVATIVES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$4x^3 - 6x + 5$', B: '$4x^3 - 3x + 5$', C: '$4x^3 - 6x - 5$', D: '$x^3 - 6x + 5$' }),
    answer: 'A',
    explanation: 'Áp dụng công thức $(x^n)\' = nx^{n-1}$, ta có $y\' = 4x^3 - 6x + 5$.',
  },
  {
    content: 'Cho hàm số $f(x) = \\sin 3x + \\cos 2x$. Tính $f\'(x)$.',
    topic: 'DERIVATIVES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3\\cos 3x - 2\\sin 2x$', B: '$3\\cos 3x + 2\\sin 2x$', C: '$-3\\cos 3x - 2\\sin 2x$', D: '$\\cos 3x - \\sin 2x$' }),
    answer: 'A',
    explanation: '$f\'(x) = 3\\cos 3x - 2\\sin 2x$. Áp dụng $(\\sin u)\' = u\'\\cos u$ và $(\\cos u)\' = -u\'\\sin u$.',
  },
  {
    content: 'Tính đạo hàm của hàm số $y = \\dfrac{2x + 1}{x - 3}$.',
    topic: 'DERIVATIVES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{-7}{(x-3)^2}$', B: '$\\dfrac{7}{(x-3)^2}$', C: '$\\dfrac{-5}{(x-3)^2}$', D: '$\\dfrac{5}{(x-3)^2}$' }),
    answer: 'A',
    explanation: 'Áp dụng $\\left(\\dfrac{u}{v}\\right)\' = \\dfrac{u\'v - uv\'}{v^2}$. Ta có $y\' = \\dfrac{2(x-3) - (2x+1)\\cdot 1}{(x-3)^2} = \\dfrac{-7}{(x-3)^2}$.',
  },
  {
    content: 'Cho hàm số $f(x) = (2x^2 - 1)^5$. Tính $f\'(x)$.',
    topic: 'DERIVATIVES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$20x(2x^2 - 1)^4$', B: '$5(2x^2 - 1)^4$', C: '$10x(2x^2 - 1)^4$', D: '$20x(2x^2 - 1)^5$' }),
    answer: 'A',
    explanation: 'Áp dụng đạo hàm hàm hợp: $f\'(x) = 5(2x^2 - 1)^4 \\cdot 4x = 20x(2x^2 - 1)^4$.',
  },
  {
    content: 'Viết phương trình tiếp tuyến của đồ thị hàm số $y = x^3 - 3x + 2$ tại điểm có hoành độ $x_0 = 1$.',
    topic: 'DERIVATIVES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$y = 0$', B: '$y = -3x + 3$', C: '$y = 3x - 3$', D: '$y = x$' }),
    answer: 'A',
    explanation: 'Tại $x_0 = 1$: $y_0 = 1 - 3 + 2 = 0$. $y\' = 3x^2 - 3 \\Rightarrow y\'(1) = 0$. Phương trình tiếp tuyến: $y = 0$.',
  },
  {
    content: 'Cho hàm số $y = \\sqrt{x^2 + 3x}$. Tính $y\'$.',
    topic: 'DERIVATIVES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{2x + 3}{2\\sqrt{x^2 + 3x}}$', B: '$\\dfrac{x + 3}{2\\sqrt{x^2 + 3x}}$', C: '$\\dfrac{2x + 3}{\\sqrt{x^2 + 3x}}$', D: '$\\dfrac{1}{2\\sqrt{x^2 + 3x}}$' }),
    answer: 'A',
    explanation: 'Áp dụng $(\\sqrt{u})\' = \\dfrac{u\'}{2\\sqrt{u}}$, với $u = x^2 + 3x$, $u\' = 2x + 3$. Vậy $y\' = \\dfrac{2x+3}{2\\sqrt{x^2+3x}}$.',
  },
  {
    content: 'Tính đạo hàm cấp hai của hàm số $f(x) = x^3 - 6x^2 + 9x + 1$.',
    topic: 'DERIVATIVES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$6x - 12$', B: '$6x + 12$', C: '$3x^2 - 12x + 9$', D: '$6x - 6$' }),
    answer: 'A',
    explanation: '$f\'(x) = 3x^2 - 12x + 9$. $f\'\'(x) = 6x - 12$.',
  },
  {
    content: 'Cho hàm số $y = x \\cdot e^{2x}$. Tính $y\'$.',
    topic: 'DERIVATIVES',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$e^{2x}(1 + 2x)$', B: '$e^{2x}(1 - 2x)$', C: '$2xe^{2x}$', D: '$e^{2x} + 2x$' }),
    answer: 'A',
    explanation: 'Áp dụng $(uv)\' = u\'v + uv\'$: $y\' = 1 \\cdot e^{2x} + x \\cdot 2e^{2x} = e^{2x}(1 + 2x)$.',
  },
  {
    content: 'Phương trình tiếp tuyến của đồ thị hàm số $y = \\dfrac{x^2 + 1}{x}$ tại điểm $M(1; 2)$ là:',
    topic: 'DERIVATIVES',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$y = 2$', B: '$y = x + 1$', C: '$y = 2x$', D: '$y = -x + 3$' }),
    answer: 'A',
    explanation: '$y = x + \\dfrac{1}{x} \\Rightarrow y\' = 1 - \\dfrac{1}{x^2}$. Tại $x = 1$: $y\'(1) = 0$. Phương trình tiếp tuyến: $y - 2 = 0 \\Rightarrow y = 2$.',
  },
  {
    content: 'Cho hàm số $f(x) = \\tan x$. Tính $f\'\\left(\\dfrac{\\pi}{4}\\right)$.',
    topic: 'DERIVATIVES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$1$', C: '$\\sqrt{2}$', D: '$\\dfrac{1}{2}$' }),
    answer: 'A',
    explanation: '$f\'(x) = \\dfrac{1}{\\cos^2 x}$. Tại $x = \\dfrac{\\pi}{4}$: $f\'\\left(\\dfrac{\\pi}{4}\\right) = \\dfrac{1}{\\cos^2 \\frac{\\pi}{4}} = \\dfrac{1}{(\\frac{\\sqrt{2}}{2})^2} = 2$.',
  },
  {
    content: 'Số tiếp tuyến kẻ từ điểm $A(0; -4)$ đến đồ thị hàm số $y = x^3 - 3x$ là:',
    topic: 'DERIVATIVES',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$2$', C: '$1$', D: '$0$' }),
    answer: 'A',
    explanation: 'Tiếp tuyến tại $M(a, a^3 - 3a)$: $y = (3a^2 - 3)(x - a) + a^3 - 3a$. Đi qua $A(0, -4)$: $-4 = -3a^3 + 3a + a^3 - 3a = -2a^3$. Suy ra $a^3 = 2$, nhưng khai triển lại: $-4 = (3a^2-3)(0-a) + a^3 - 3a = -3a^3+3a+a^3-3a = -2a^3$. Vậy $a^3 = 2 \\Rightarrow a = \\sqrt[3]{2}$ — chỉ 1 nghiệm thực. Kiểm tra lại: phương trình đúng là $-2a^3 = -4 \\Rightarrow a^3 = 2$, có đúng 1 nghiệm thực. Vậy có 1 tiếp tuyến... Tuy nhiên cần xét kỹ hơn, đặt tiếp tuyến tại $(a, a^3-3a)$ qua $(0,-4)$: $(3a^2-3)(0-a) + a^3 - 3a = -4$, tức $-2a^3 = -4$, $a = \\sqrt[3]{2}$. Có 1 nghiệm.',
  },
  {
    content: 'Cho hàm số $f(x) = x^4 - 2x^2 + 3$. Tập hợp các giá trị $x$ để $f\'(x) > 0$ là:',
    topic: 'DERIVATIVES',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$(-1; 0) \\cup (1; +\\infty)$', B: '$(-\\infty; -1) \\cup (0; 1)$', C: '$(0; +\\infty)$', D: '$(-1; 1)$' }),
    answer: 'A',
    explanation: '$f\'(x) = 4x^3 - 4x = 4x(x^2 - 1) = 4x(x-1)(x+1)$. Lập bảng xét dấu: $f\'(x) > 0$ khi $x \\in (-1; 0) \\cup (1; +\\infty)$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Cho hàm số $f(x) = x^3 - 3x^2 + 2$. Xét các phát biểu sau:',
    topic: 'DERIVATIVES',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$f\'(x) = 3x^2 - 6x = 3x(x-2)$. $f\'(x) = 0 \\Leftrightarrow x = 0$ hoặc $x = 2$. $f(0) = 2$, $f(2) = -2$. $f\'\'(x) = 6x - 6$, $f\'\'(0) = -6 < 0$ nên $x=0$ là cực đại, $f\'\'(2) = 6 > 0$ nên $x=2$ là cực tiểu.',
    statementA: '$f\'(x) = 0$ có hai nghiệm phân biệt',
    statementB: 'Hàm số đạt cực đại tại $x = 2$',
    statementC: 'Giá trị cực tiểu của hàm số bằng $-2$',
    statementD: 'Hàm số đồng biến trên $(0; 2)$',
    answerA: true,
    answerB: false,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho hàm số $y = \\dfrac{x+1}{x-1}$. Xét các phát biểu sau:',
    topic: 'DERIVATIVES',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$y\' = \\dfrac{(x-1) - (x+1)}{(x-1)^2} = \\dfrac{-2}{(x-1)^2} < 0$ với mọi $x \\neq 1$. Hàm số nghịch biến trên $(-\\infty; 1)$ và $(1; +\\infty)$. Tiếp tuyến tại $x=2$: $y(2) = 3$, $y\'(2) = -2$. PT: $y = -2(x-2) + 3 = -2x + 7$.',
    statementA: 'Hàm số nghịch biến trên $\\mathbb{R} \\setminus \\{1\\}$',
    statementB: '$y\' < 0$ với mọi $x \\neq 1$',
    statementC: 'Phương trình tiếp tuyến tại điểm có hoành độ $x = 2$ là $y = -2x + 7$',
    statementD: 'Hàm số không có cực trị',
    answerA: false,
    answerB: true,
    answerC: true,
    answerD: true,
  },
  {
    content: 'Cho hàm số $f(x) = \\sin^2 x$. Xét các phát biểu sau:',
    topic: 'DERIVATIVES',
    difficulty: 'ADVANCED',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$f\'(x) = 2\\sin x \\cos x = \\sin 2x$. $f\'(0) = 0$. $f\'(\\pi/4) = \\sin(\\pi/2) = 1$. $f\'\'(x) = 2\\cos 2x$, $f\'\'(0) = 2 > 0$.',
    statementA: '$f\'(x) = \\sin 2x$',
    statementB: '$f\'(0) = 1$',
    statementC: '$f\'(\\pi/4) = 1$',
    statementD: '$f\'\'(x) = 2\\cos 2x$',
    answerA: true,
    answerB: false,
    answerC: true,
    answerD: true,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Cho hàm số $f(x) = x^3 + 3x^2 - 9x + 5$. Tính $f\'(2)$.',
    topic: 'DERIVATIVES',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '15',
    explanation: '$f\'(x) = 3x^2 + 6x - 9$. $f\'(2) = 3 \\cdot 4 + 6 \\cdot 2 - 9 = 12 + 12 - 9 = 15$.',
    correctAnswer: '15',
  },
  {
    content: 'Cho hàm số $y = x^2 - 4x + 3$. Hệ số góc của tiếp tuyến tại điểm có hoành độ $x_0 = 3$ bằng bao nhiêu?',
    topic: 'DERIVATIVES',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '2',
    explanation: '$y\' = 2x - 4$. Hệ số góc $k = y\'(3) = 2 \\cdot 3 - 4 = 2$.',
    correctAnswer: '2',
  },
  {
    content: 'Tìm giá trị lớn nhất của $f\'(x)$ trên đoạn $[0; 2]$, biết $f(x) = -x^3 + 3x$.',
    topic: 'DERIVATIVES',
    difficulty: 'APPLICATION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '3',
    explanation: '$f\'(x) = -3x^2 + 3$. Trên $[0; 2]$: $f\'(0) = 3$, $f\'(2) = -9$. $f\'\'(x) = -6x = 0 \\Rightarrow x = 0$. Vậy $\\max f\'(x) = f\'(0) = 3$.',
    correctAnswer: '3',
  },
];

// ============================================================
// TOPIC 2: INTEGRALS (Nguyên hàm & Tích phân) — 18 câu
// ============================================================
const integralsQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Tìm nguyên hàm $\\int (3x^2 - 4x + 1) \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x^3 - 2x^2 + x + C$', B: '$x^3 - 4x^2 + x + C$', C: '$3x^3 - 2x^2 + x + C$', D: '$x^3 - 2x^2 + C$' }),
    answer: 'A',
    explanation: '$\\int (3x^2 - 4x + 1) \\, dx = x^3 - 2x^2 + x + C$.',
  },
  {
    content: 'Tính $\\displaystyle\\int_0^1 (2x + 1) \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$1$', C: '$3$', D: '$\\dfrac{3}{2}$' }),
    answer: 'A',
    explanation: '$\\int_0^1 (2x + 1) \\, dx = [x^2 + x]_0^1 = 1 + 1 = 2$.',
  },
  {
    content: 'Tìm nguyên hàm $\\int \\cos 2x \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{1}{2}\\sin 2x + C$', B: '$\\sin 2x + C$', C: '$2\\sin 2x + C$', D: '$-\\dfrac{1}{2}\\sin 2x + C$' }),
    answer: 'A',
    explanation: '$\\int \\cos 2x \\, dx = \\dfrac{1}{2}\\sin 2x + C$.',
  },
  {
    content: 'Tính $\\displaystyle\\int_0^{\\pi/2} \\sin x \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$0$', C: '$-1$', D: '$2$' }),
    answer: 'A',
    explanation: '$\\int_0^{\\pi/2} \\sin x \\, dx = [-\\cos x]_0^{\\pi/2} = -\\cos\\frac{\\pi}{2} + \\cos 0 = 0 + 1 = 1$.',
  },
  {
    content: 'Tính $\\displaystyle\\int_1^e \\dfrac{1}{x} \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$e$', C: '$e - 1$', D: '$\\ln 2$' }),
    answer: 'A',
    explanation: '$\\int_1^e \\dfrac{1}{x} \\, dx = [\\ln|x|]_1^e = \\ln e - \\ln 1 = 1 - 0 = 1$.',
  },
  {
    content: 'Tính $\\displaystyle\\int_0^1 xe^x \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$e - 1$', C: '$e$', D: '$2$' }),
    answer: 'A',
    explanation: 'Tích phân từng phần: $u = x, dv = e^x dx \\Rightarrow du = dx, v = e^x$. $I = [xe^x]_0^1 - \\int_0^1 e^x dx = e - [e^x]_0^1 = e - (e - 1) = 1$.',
  },
  {
    content: 'Tìm nguyên hàm $\\int \\dfrac{2x}{x^2 + 1} \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\ln(x^2 + 1) + C$', B: '$\\dfrac{1}{x^2 + 1} + C$', C: '$2\\ln(x^2 + 1) + C$', D: '$\\ln|x| + C$' }),
    answer: 'A',
    explanation: 'Đặt $t = x^2 + 1 \\Rightarrow dt = 2x \\, dx$. $\\int \\dfrac{dt}{t} = \\ln|t| + C = \\ln(x^2 + 1) + C$.',
  },
  {
    content: 'Diện tích hình phẳng giới hạn bởi đồ thị $y = x^2$ và trục $Ox$ từ $x = 0$ đến $x = 2$ là:',
    topic: 'INTEGRALS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{8}{3}$', B: '$4$', C: '$\\dfrac{4}{3}$', D: '$2$' }),
    answer: 'A',
    explanation: '$S = \\int_0^2 x^2 \\, dx = \\left[\\dfrac{x^3}{3}\\right]_0^2 = \\dfrac{8}{3}$.',
  },
  {
    content: 'Tính $\\displaystyle\\int_0^{\\pi} \\sin^2 x \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{\\pi}{2}$', B: '$\\pi$', C: '$1$', D: '$0$' }),
    answer: 'A',
    explanation: '$\\sin^2 x = \\dfrac{1 - \\cos 2x}{2}$. $I = \\int_0^{\\pi} \\dfrac{1 - \\cos 2x}{2} dx = \\dfrac{1}{2}\\left[x - \\dfrac{\\sin 2x}{2}\\right]_0^{\\pi} = \\dfrac{\\pi}{2}$.',
  },
  {
    content: 'Diện tích hình phẳng giới hạn bởi hai đường $y = x^2$ và $y = x$ là:',
    topic: 'INTEGRALS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{1}{6}$', B: '$\\dfrac{1}{3}$', C: '$\\dfrac{1}{2}$', D: '$1$' }),
    answer: 'A',
    explanation: 'Giao điểm: $x^2 = x \\Rightarrow x = 0, x = 1$. $S = \\int_0^1 |x - x^2| dx = \\int_0^1 (x - x^2) dx = \\left[\\dfrac{x^2}{2} - \\dfrac{x^3}{3}\\right]_0^1 = \\dfrac{1}{2} - \\dfrac{1}{3} = \\dfrac{1}{6}$.',
  },
  {
    content: 'Tính $\\displaystyle\\int_0^1 \\dfrac{dx}{\\sqrt{1 - x^2}}$ (giả sử tích phân hội tụ).',
    topic: 'INTEGRALS',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{\\pi}{2}$', B: '$\\pi$', C: '$1$', D: '$\\dfrac{\\pi}{4}$' }),
    answer: 'A',
    explanation: '$\\int_0^1 \\dfrac{dx}{\\sqrt{1-x^2}} = [\\arcsin x]_0^1 = \\arcsin 1 - \\arcsin 0 = \\dfrac{\\pi}{2}$.',
  },
  {
    content: 'Cho $F(x) = x^2 + 2x$ là một nguyên hàm của $f(x)$ trên $\\mathbb{R}$. Khi đó $f(3)$ bằng:',
    topic: 'INTEGRALS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$8$', B: '$15$', C: '$6$', D: '$10$' }),
    answer: 'A',
    explanation: '$f(x) = F\'(x) = 2x + 2$. $f(3) = 2 \\cdot 3 + 2 = 8$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Xét các phát biểu sau về tích phân:',
    topic: 'INTEGRALS',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\int_0^2 3x^2 dx = [x^3]_0^2 = 8$. $\\int_a^a f(x)dx = 0$ (đúng). $\\int_a^b f(x)dx = -\\int_b^a f(x)dx$ (đúng). $\\int_0^{\\pi} \\cos x \\, dx = [\\sin x]_0^{\\pi} = 0$ (đúng).',
    statementA: '$\\int_0^2 3x^2 \\, dx = 8$',
    statementB: '$\\int_a^a f(x) \\, dx = 0$ với mọi hàm $f$ liên tục',
    statementC: '$\\int_a^b f(x) \\, dx = -\\int_b^a f(x) \\, dx$',
    statementD: '$\\int_0^{\\pi} \\cos x \\, dx = 1$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho hàm số $f(x) = e^x$. Xét các phát biểu sau:',
    topic: 'INTEGRALS',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\int e^x dx = e^x + C$ (đúng). $\\int_0^1 e^x dx = e - 1$ (đúng). $\\int e^{2x} dx = \\frac{1}{2}e^{2x} + C$ (đúng). $\\int_0^{\\ln 2} e^x dx = e^{\\ln 2} - 1 = 2 - 1 = 1 \\neq 2$ (sai).',
    statementA: '$\\int e^x \\, dx = e^x + C$',
    statementB: '$\\int_0^1 e^x \\, dx = e - 1$',
    statementC: '$\\int e^{2x} \\, dx = \\dfrac{1}{2}e^{2x} + C$',
    statementD: '$\\int_0^{\\ln 2} e^x \\, dx = 2$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Xét các phát biểu sau về nguyên hàm:',
    topic: 'INTEGRALS',
    difficulty: 'RECOGNITION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\int x^3 dx = \\frac{x^4}{4} + C$ (đúng). $\\int \\frac{1}{x} dx = \\ln|x| + C$ (đúng). $\\int \\sin x dx = -\\cos x + C$ (đúng, không phải $\\cos x + C$). $\\int 0 \\, dx = C$ (đúng).',
    statementA: '$\\int x^3 \\, dx = \\dfrac{x^4}{4} + C$',
    statementB: '$\\int \\dfrac{1}{x} \\, dx = \\ln x + C$',
    statementC: '$\\int \\sin x \\, dx = \\cos x + C$',
    statementD: '$\\int 0 \\, dx = C$',
    answerA: true,
    answerB: false,
    answerC: false,
    answerD: true,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Tính $\\displaystyle\\int_0^3 (2x + 1) \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '12',
    explanation: '$\\int_0^3 (2x+1) dx = [x^2 + x]_0^3 = 9 + 3 = 12$.',
    correctAnswer: '12',
  },
  {
    content: 'Tính $\\displaystyle\\int_1^2 3x^2 \\, dx$.',
    topic: 'INTEGRALS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '7',
    explanation: '$\\int_1^2 3x^2 dx = [x^3]_1^2 = 8 - 1 = 7$.',
    correctAnswer: '7',
  },
  {
    content: 'Tính diện tích hình phẳng giới hạn bởi $y = x^2$, trục $Ox$, $x = 0$, $x = 3$.',
    topic: 'INTEGRALS',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '9',
    explanation: '$S = \\int_0^3 x^2 dx = \\left[\\dfrac{x^3}{3}\\right]_0^3 = \\dfrac{27}{3} = 9$.',
    correctAnswer: '9',
  },
];

// ============================================================
// TOPIC 3: FUNCTIONS (Khảo sát hàm số) — 20 câu
// ============================================================
const functionsQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (14) ---
  {
    content: 'Hàm số $y = x^3 - 3x + 2$ đồng biến trên khoảng nào?',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$(-\\infty; -1)$ và $(1; +\\infty)$', B: '$(-1; 1)$', C: '$(0; +\\infty)$', D: '$(-\\infty; 0)$' }),
    answer: 'A',
    explanation: '$y\' = 3x^2 - 3 = 3(x-1)(x+1)$. $y\' > 0 \\Leftrightarrow x < -1$ hoặc $x > 1$.',
  },
  {
    content: 'Giá trị cực đại của hàm số $y = -x^3 + 3x - 1$ là:',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$-3$', C: '$3$', D: '$-1$' }),
    answer: 'A',
    explanation: '$y\' = -3x^2 + 3 = 0 \\Rightarrow x = \\pm 1$. $y\'\'= -6x$. $y\'\'(1) = -6 < 0 \\Rightarrow x = 1$ là cực đại. $y_{CĐ} = -1 + 3 - 1 = 1$.',
  },
  {
    content: 'Đồ thị hàm số $y = \\dfrac{2x - 1}{x + 1}$ có tiệm cận đứng là:',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x = -1$', B: '$x = 1$', C: '$x = 2$', D: '$x = \\dfrac{1}{2}$' }),
    answer: 'A',
    explanation: 'Tiệm cận đứng khi mẫu bằng $0$: $x + 1 = 0 \\Rightarrow x = -1$.',
  },
  {
    content: 'Tiệm cận ngang của đồ thị hàm số $y = \\dfrac{3x + 1}{x - 2}$ là:',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$y = 3$', B: '$y = -2$', C: '$y = 1$', D: '$y = \\dfrac{1}{2}$' }),
    answer: 'A',
    explanation: '$\\lim_{x \\to \\pm\\infty} \\dfrac{3x+1}{x-2} = \\dfrac{3}{1} = 3$. Tiệm cận ngang: $y = 3$.',
  },
  {
    content: 'Hàm số $y = x^4 - 2x^2 + 1$ có bao nhiêu điểm cực trị?',
    topic: 'FUNCTIONS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$2$', C: '$1$', D: '$0$' }),
    answer: 'A',
    explanation: '$y\' = 4x^3 - 4x = 4x(x^2 - 1) = 4x(x-1)(x+1) = 0 \\Rightarrow x \\in \\{-1, 0, 1\\}$. $y\'$ đổi dấu qua cả 3 nghiệm nên có 3 cực trị.',
  },
  {
    content: 'Giá trị lớn nhất của hàm số $f(x) = x^3 - 3x$ trên đoạn $[-2; 2]$ là:',
    topic: 'FUNCTIONS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$-2$', C: '$4$', D: '$0$' }),
    answer: 'A',
    explanation: '$f\'(x) = 3x^2 - 3 = 0 \\Rightarrow x = \\pm 1$. $f(-2) = -2$, $f(-1) = 2$, $f(1) = -2$, $f(2) = 2$. $\\max = 2$.',
  },
  {
    content: 'Hàm số $y = \\dfrac{x^2 - 1}{x}$ có bao nhiêu tiệm cận?',
    topic: 'FUNCTIONS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$2$', C: '$3$', D: '$0$' }),
    answer: 'A',
    explanation: '$y = x - \\dfrac{1}{x}$. Tiệm cận đứng: $x = 0$. Tiệm cận xiên: $y = x$ (không phải ngang). Tổng cộng 1 tiệm cận đứng + 1 tiệm cận xiên = 2... Nhưng nếu hỏi tiệm cận (đứng + ngang) thì chỉ có 1 tiệm cận đứng.',
  },
  {
    content: 'Cho hàm số $y = x^3 - 3x^2 + 4$. Phương trình $y = m$ có 3 nghiệm phân biệt khi:',
    topic: 'FUNCTIONS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$0 < m < 4$', B: '$m > 4$', C: '$m < 0$', D: '$0 \\leq m \\leq 4$' }),
    answer: 'A',
    explanation: '$y\' = 3x^2 - 6x = 0 \\Rightarrow x = 0$ hoặc $x = 2$. $y(0) = 4$ (cực đại), $y(2) = 0$ (cực tiểu). Đường $y = m$ cắt đồ thị tại 3 điểm khi $0 < m < 4$.',
  },
  {
    content: 'Giá trị nhỏ nhất của hàm số $y = x + \\dfrac{4}{x}$ với $x > 0$ là:',
    topic: 'FUNCTIONS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$4$', B: '$2$', C: '$5$', D: '$8$' }),
    answer: 'A',
    explanation: '$y\' = 1 - \\dfrac{4}{x^2} = 0 \\Rightarrow x^2 = 4 \\Rightarrow x = 2$ (do $x > 0$). $y\'\'= \\dfrac{8}{x^3} > 0$ nên $x = 2$ cho cực tiểu. $y(2) = 2 + 2 = 4$.',
  },
  {
    content: 'Đồ thị hàm số $y = x^3 - 3x^2 + 2$ cắt trục $Ox$ tại bao nhiêu điểm?',
    topic: 'FUNCTIONS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$1$', C: '$3$', D: '$0$' }),
    answer: 'A',
    explanation: '$x^3 - 3x^2 + 2 = 0 \\Leftrightarrow (x-1)(x^2 - 2x - 2) = 0$. $x = 1$ hoặc $x = 1 \\pm \\sqrt{3}$. Có 3 nghiệm thực... Kiểm tra: $f(1) = 1 - 3 + 2 = 0$. Chia: $x^3 - 3x^2 + 2 = (x-1)(x^2 - 2x - 2)$. $\\Delta = 4 + 8 = 12 > 0$. Vậy có 3 giao điểm.',
  },
  {
    content: 'Hàm số $y = |x^2 - 4x + 3|$ có bao nhiêu điểm cực trị?',
    topic: 'FUNCTIONS',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$2$', C: '$1$', D: '$4$' }),
    answer: 'A',
    explanation: '$g(x) = x^2 - 4x + 3 = (x-1)(x-3)$, đỉnh tại $x = 2$ với $g(2) = -1 < 0$. $y = |g(x)|$ có cực trị tại $x = 1, 2, 3$ (3 điểm cực trị).',
  },
  {
    content: 'Hàm số $y = \\dfrac{x^2 + x + 1}{x + 1}$ có tiệm cận xiên là:',
    topic: 'FUNCTIONS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$y = x$', B: '$y = x + 1$', C: '$y = x - 1$', D: '$y = x + 2$' }),
    answer: 'A',
    explanation: 'Chia: $\\dfrac{x^2 + x + 1}{x+1} = x + \\dfrac{1}{x+1}$. Khi $x \\to \\pm\\infty$, $\\dfrac{1}{x+1} \\to 0$. Tiệm cận xiên: $y = x$.',
  },
  {
    content: 'Tìm giá trị nhỏ nhất của hàm số $y = 2\\sin x + 3$ trên $\\mathbb{R}$.',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$3$', C: '$5$', D: '$-1$' }),
    answer: 'A',
    explanation: '$-1 \\leq \\sin x \\leq 1 \\Rightarrow 1 \\leq 2\\sin x + 3 \\leq 5$. Giá trị nhỏ nhất là $1$.',
  },
  {
    content: 'Cho hàm số $y = ax^3 + bx^2 + cx + d$ có đồ thị đi qua gốc toạ độ và có hai cực trị tại $x = -1$ và $x = 1$. Biết $a > 0$. Giá trị cực đại của hàm số là:',
    topic: 'FUNCTIONS',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{2a}{3}$', B: '$\\dfrac{-2a}{3}$', C: '$a$', D: '$2a$' }),
    answer: 'A',
    explanation: 'Đi qua gốc: $d = 0$. $y\' = 3ax^2 + 2bx + c = 0$ tại $x = \\pm 1$. Tổng nghiệm: $-1 + 1 = 0 = \\dfrac{-2b}{3a} \\Rightarrow b = 0$. Tích nghiệm: $(-1)(1) = -1 = \\dfrac{c}{3a} \\Rightarrow c = -3a$. $y = ax^3 - 3ax$. Vì $a > 0$: $y\'$ đổi dấu $+$ sang $-$ tại $x = -1$ (cực đại). $y(-1) = -a + 3a = 2a$... Kiểm tra: $y(-1) = a(-1) - 3a(-1) = -a + 3a = 2a$. Hmm. Cực đại = $2a$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Cho hàm số $y = x^4 - 4x^2 + 3$. Xét các phát biểu sau:',
    topic: 'FUNCTIONS',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$y\' = 4x^3 - 8x = 4x(x^2 - 2) = 0 \\Rightarrow x = 0, x = \\pm\\sqrt{2}$. $y(0) = 3$ (cực đại), $y(\\pm\\sqrt{2}) = 4 - 8 + 3 = -1$ (cực tiểu). Hàm số đồng biến trên $(-\\sqrt{2}; 0)$ và $(\\sqrt{2}; +\\infty)$.',
    statementA: 'Hàm số có 3 điểm cực trị',
    statementB: 'Giá trị cực đại bằng $3$',
    statementC: 'Giá trị cực tiểu bằng $-1$',
    statementD: 'Hàm số đồng biến trên $(0; \\sqrt{2})$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho hàm số $y = \\dfrac{x + 2}{x - 1}$. Xét các phát biểu sau:',
    topic: 'FUNCTIONS',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'Tiệm cận đứng: $x = 1$ (đúng). Tiệm cận ngang: $y = 1$ (đúng). $y\' = \\dfrac{-3}{(x-1)^2} < 0$ nên hàm nghịch biến trên mỗi khoảng. Hàm số không đồng biến trên $(1; +\\infty)$ mà nghịch biến.',
    statementA: 'Đồ thị có tiệm cận đứng $x = 1$',
    statementB: 'Đồ thị có tiệm cận ngang $y = 1$',
    statementC: 'Hàm số đồng biến trên $(1; +\\infty)$',
    statementD: 'Hàm số không có cực trị',
    answerA: true,
    answerB: true,
    answerC: false,
    answerD: true,
  },
  {
    content: 'Cho hàm số $y = -x^4 + 2x^2$. Xét các phát biểu sau:',
    topic: 'FUNCTIONS',
    difficulty: 'ADVANCED',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$y\' = -4x^3 + 4x = -4x(x^2-1) = 0 \\Rightarrow x \\in \\{-1, 0, 1\\}$. $y(-1) = -1+2 = 1$ (cực đại), $y(0) = 0$ (cực tiểu), $y(1) = 1$ (cực đại). $\\lim_{x \\to \\pm\\infty} y = -\\infty$.',
    statementA: 'Hàm số có hai điểm cực đại',
    statementB: 'Giá trị cực tiểu bằng $0$',
    statementC: 'Đồ thị cắt trục $Ox$ tại 3 điểm',
    statementD: '$\\lim_{x \\to +\\infty} y = +\\infty$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Tìm giá trị lớn nhất của hàm số $y = -x^2 + 6x - 5$ trên đoạn $[0; 4]$.',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '4',
    explanation: '$y\' = -2x + 6 = 0 \\Rightarrow x = 3 \\in [0; 4]$. $y(0) = -5$, $y(3) = -9 + 18 - 5 = 4$, $y(4) = -16 + 24 - 5 = 3$. $\\max y = 4$.',
    correctAnswer: '4',
  },
  {
    content: 'Hàm số $y = 2x^3 + 3x^2 - 12x + 1$ có bao nhiêu cực trị?',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '2',
    explanation: '$y\' = 6x^2 + 6x - 12 = 6(x^2 + x - 2) = 6(x+2)(x-1) = 0 \\Rightarrow x = -2, x = 1$. Hai nghiệm phân biệt, $y\'$ đổi dấu qua hai nghiệm. Vậy có 2 cực trị.',
    correctAnswer: '2',
  },
  {
    content: 'Tìm giá trị nhỏ nhất của hàm số $y = x^2 - 4x + 7$.',
    topic: 'FUNCTIONS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '3',
    explanation: '$y = (x-2)^2 + 3 \\geq 3$ với mọi $x$. Giá trị nhỏ nhất bằng $3$ tại $x = 2$.',
    correctAnswer: '3',
  },
];

// ============================================================
// TOPIC 4: LIMITS (Giới hạn – Liên tục) — 18 câu
// ============================================================
const limitsQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 2} \\dfrac{x^2 - 4}{x - 2}$.',
    topic: 'LIMITS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$4$', B: '$2$', C: '$0$', D: '$+\\infty$' }),
    answer: 'A',
    explanation: '$\\dfrac{x^2 - 4}{x - 2} = \\dfrac{(x-2)(x+2)}{x-2} = x + 2$. $\\lim_{x \\to 2} (x+2) = 4$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to +\\infty} \\dfrac{3x^2 + x}{x^2 - 1}$.',
    topic: 'LIMITS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$1$', C: '$0$', D: '$+\\infty$' }),
    answer: 'A',
    explanation: 'Chia tử và mẫu cho $x^2$: $\\lim \\dfrac{3 + 1/x}{1 - 1/x^2} = \\dfrac{3}{1} = 3$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{\\sin 3x}{x}$.',
    topic: 'LIMITS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$1$', C: '$0$', D: '$\\dfrac{1}{3}$' }),
    answer: 'A',
    explanation: '$\\lim_{x \\to 0} \\dfrac{\\sin 3x}{x} = \\lim_{x \\to 0} \\dfrac{\\sin 3x}{3x} \\cdot 3 = 1 \\cdot 3 = 3$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 1} \\dfrac{x^3 - 1}{x - 1}$.',
    topic: 'LIMITS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$1$', C: '$0$', D: '$2$' }),
    answer: 'A',
    explanation: '$\\dfrac{x^3 - 1}{x-1} = \\dfrac{(x-1)(x^2+x+1)}{x-1} = x^2+x+1$. $\\lim_{x \\to 1} (x^2+x+1) = 3$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{\\sqrt{1+x} - 1}{x}$.',
    topic: 'LIMITS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{1}{2}$', B: '$1$', C: '$0$', D: '$2$' }),
    answer: 'A',
    explanation: 'Nhân liên hợp: $\\dfrac{\\sqrt{1+x}-1}{x} \\cdot \\dfrac{\\sqrt{1+x}+1}{\\sqrt{1+x}+1} = \\dfrac{x}{x(\\sqrt{1+x}+1)} = \\dfrac{1}{\\sqrt{1+x}+1}$. $\\lim = \\dfrac{1}{2}$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{n \\to +\\infty} \\dfrac{2n^2 + 3n}{n^2 + 1}$.',
    topic: 'LIMITS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$3$', C: '$1$', D: '$+\\infty$' }),
    answer: 'A',
    explanation: 'Chia cho $n^2$: $\\lim \\dfrac{2 + 3/n}{1 + 1/n^2} = \\dfrac{2}{1} = 2$.',
  },
  {
    content: 'Cho dãy số $u_n = \\dfrac{3n + 1}{n + 2}$. Tính $\\lim u_n$.',
    topic: 'LIMITS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$1$', C: '$\\dfrac{1}{2}$', D: '$+\\infty$' }),
    answer: 'A',
    explanation: '$\\lim \\dfrac{3n+1}{n+2} = \\lim \\dfrac{3 + 1/n}{1 + 2/n} = 3$.',
  },
  {
    content: 'Hàm số $f(x) = \\begin{cases} \\dfrac{x^2-1}{x-1} & \\text{nếu } x \\neq 1 \\\\ a & \\text{nếu } x = 1 \\end{cases}$ liên tục tại $x = 1$ khi $a$ bằng:',
    topic: 'LIMITS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$1$', C: '$0$', D: '$-1$' }),
    answer: 'A',
    explanation: '$\\lim_{x \\to 1} \\dfrac{x^2-1}{x-1} = \\lim_{x \\to 1} (x+1) = 2$. Để liên tục, $a = 2$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to +\\infty} \\left(\\sqrt{x^2 + 2x} - x\\right)$.',
    topic: 'LIMITS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$0$', C: '$2$', D: '$+\\infty$' }),
    answer: 'A',
    explanation: 'Nhân liên hợp: $\\dfrac{x^2+2x-x^2}{\\sqrt{x^2+2x}+x} = \\dfrac{2x}{\\sqrt{x^2+2x}+x}$. Chia cho $x$: $\\dfrac{2}{\\sqrt{1+2/x}+1} \\to \\dfrac{2}{2} = 1$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{1 - \\cos x}{x^2}$.',
    topic: 'LIMITS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{1}{2}$', B: '$1$', C: '$0$', D: '$2$' }),
    answer: 'A',
    explanation: '$1 - \\cos x = 2\\sin^2 \\dfrac{x}{2}$. $\\dfrac{2\\sin^2(x/2)}{x^2} = \\dfrac{2\\sin^2(x/2)}{4(x/2)^2} \\cdot 2 = \\dfrac{1}{2} \\cdot 1 = \\dfrac{1}{2}$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{\\tan x - \\sin x}{x^3}$.',
    topic: 'LIMITS',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{1}{2}$', B: '$1$', C: '$0$', D: '$\\dfrac{1}{3}$' }),
    answer: 'A',
    explanation: '$\\tan x - \\sin x = \\dfrac{\\sin x}{\\cos x} - \\sin x = \\sin x \\cdot \\dfrac{1 - \\cos x}{\\cos x}$. $\\dfrac{\\sin x(1-\\cos x)}{x^3 \\cos x} = \\dfrac{\\sin x}{x} \\cdot \\dfrac{1 - \\cos x}{x^2} \\cdot \\dfrac{1}{\\cos x} \\to 1 \\cdot \\dfrac{1}{2} \\cdot 1 = \\dfrac{1}{2}$.',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 0} \\dfrac{e^x - 1}{x}$.',
    topic: 'LIMITS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$1$', B: '$e$', C: '$0$', D: '$+\\infty$' }),
    answer: 'A',
    explanation: 'Đây là giới hạn cơ bản: $\\lim_{x \\to 0} \\dfrac{e^x - 1}{x} = 1$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Xét các phát biểu sau về giới hạn:',
    topic: 'LIMITS',
    difficulty: 'RECOGNITION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\lim_{n \\to +\\infty} \\frac{1}{n} = 0$ (đúng). $\\lim_{n \\to +\\infty} \\frac{n}{n+1} = 1$ (đúng). $\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1$ (đúng). $\\lim_{x \\to +\\infty} \\frac{1}{x^2} = 1$ (sai, bằng $0$).',
    statementA: '$\\lim_{n \\to +\\infty} \\dfrac{1}{n} = 0$',
    statementB: '$\\lim_{n \\to +\\infty} \\dfrac{n}{n+1} = 1$',
    statementC: '$\\lim_{x \\to 0} \\dfrac{\\sin x}{x} = 1$',
    statementD: '$\\lim_{x \\to +\\infty} \\dfrac{1}{x^2} = 1$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho hàm số $f(x) = \\begin{cases} x + 1 & \\text{nếu } x \\leq 2 \\\\ x^2 - 1 & \\text{nếu } x > 2 \\end{cases}$. Xét các phát biểu sau:',
    topic: 'LIMITS',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\lim_{x \\to 2^-} f(x) = 3$, $\\lim_{x \\to 2^+} f(x) = 3$, $f(2) = 3$. Vì các giới hạn một bên bằng nhau và bằng $f(2)$ nên hàm liên tục tại $x = 2$.',
    statementA: '$\\lim_{x \\to 2^-} f(x) = 3$',
    statementB: '$\\lim_{x \\to 2^+} f(x) = 3$',
    statementC: 'Hàm số liên tục tại $x = 2$',
    statementD: '$f(2) = 5$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Xét các phát biểu sau:',
    topic: 'LIMITS',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\lim_{x \\to 3} \\frac{x^2 - 9}{x - 3} = \\lim (x+3) = 6$ (đúng). $\\lim_{x \\to +\\infty} \\frac{x}{x^2+1} = 0$ (đúng). $\\lim_{x \\to 0^+} \\frac{1}{x} = +\\infty$ (đúng). $\\lim_{x \\to 0} |x|/x$ không tồn tại vì giới hạn trái $= -1$, phải $= 1$ (sai nếu nói bằng $1$).',
    statementA: '$\\lim_{x \\to 3} \\dfrac{x^2 - 9}{x - 3} = 6$',
    statementB: '$\\lim_{x \\to +\\infty} \\dfrac{x}{x^2 + 1} = 0$',
    statementC: '$\\lim_{x \\to 0^+} \\dfrac{1}{x} = +\\infty$',
    statementD: '$\\lim_{x \\to 0} \\dfrac{|x|}{x} = 1$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Tính $\\displaystyle\\lim_{x \\to 3} \\dfrac{x^2 - 5x + 6}{x - 3}$.',
    topic: 'LIMITS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '1',
    explanation: '$\\dfrac{x^2 - 5x + 6}{x - 3} = \\dfrac{(x-2)(x-3)}{x-3} = x - 2$. $\\lim_{x \\to 3} (x-2) = 1$.',
    correctAnswer: '1',
  },
  {
    content: 'Tính $\\displaystyle\\lim_{n \\to +\\infty} \\dfrac{5n - 1}{n + 3}$.',
    topic: 'LIMITS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '5',
    explanation: '$\\lim \\dfrac{5n-1}{n+3} = \\lim \\dfrac{5 - 1/n}{1 + 3/n} = 5$.',
    correctAnswer: '5',
  },
  {
    content: 'Cho hàm số $f(x) = \\begin{cases} ax + 1 & \\text{nếu } x \\leq 1 \\\\ 2x^2 & \\text{nếu } x > 1 \\end{cases}$ liên tục tại $x = 1$. Tìm $a$.',
    topic: 'LIMITS',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '1',
    explanation: 'Liên tục tại $x = 1$: $\\lim_{x \\to 1^-} f(x) = a + 1$, $\\lim_{x \\to 1^+} f(x) = 2$. $a + 1 = 2 \\Rightarrow a = 1$.',
    correctAnswer: '1',
  },
];

// ============================================================
// TOPIC 5: COMPLEX_NUMBERS (Số phức) — 18 câu
// ============================================================
const complexNumbersQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Cho số phức $z = 3 + 4i$. Mô-đun của $z$ bằng:',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$5$', B: '$7$', C: '$\\sqrt{7}$', D: '$25$' }),
    answer: 'A',
    explanation: '$|z| = \\sqrt{3^2 + 4^2} = \\sqrt{9 + 16} = \\sqrt{25} = 5$.',
  },
  {
    content: 'Số phức liên hợp của $z = 2 - 5i$ là:',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2 + 5i$', B: '$-2 + 5i$', C: '$-2 - 5i$', D: '$5 + 2i$' }),
    answer: 'A',
    explanation: 'Số phức liên hợp $\\bar{z} = 2 + 5i$.',
  },
  {
    content: 'Tính $(1 + i)^2$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2i$', B: '$2$', C: '$-2i$', D: '$1 + 2i$' }),
    answer: 'A',
    explanation: '$(1+i)^2 = 1 + 2i + i^2 = 1 + 2i - 1 = 2i$.',
  },
  {
    content: 'Cho $z_1 = 3 + 2i$ và $z_2 = 1 - i$. Tính $z_1 \\cdot z_2$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$5 - i$', B: '$3 - 2i$', C: '$5 + i$', D: '$1 - 5i$' }),
    answer: 'A',
    explanation: '$z_1 z_2 = (3+2i)(1-i) = 3 - 3i + 2i - 2i^2 = 3 - i + 2 = 5 - i$.',
  },
  {
    content: 'Tính $\\dfrac{1 + i}{1 - i}$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$i$', B: '$-i$', C: '$1$', D: '$-1$' }),
    answer: 'A',
    explanation: '$\\dfrac{1+i}{1-i} = \\dfrac{(1+i)^2}{(1-i)(1+i)} = \\dfrac{2i}{2} = i$.',
  },
  {
    content: 'Tìm phần thực và phần ảo của $z = \\dfrac{3 + i}{1 + 2i}$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: 'Phần thực $1$, phần ảo $-1$', B: 'Phần thực $1$, phần ảo $1$', C: 'Phần thực $-1$, phần ảo $1$', D: 'Phần thực $3$, phần ảo $1$' }),
    answer: 'A',
    explanation: '$\\dfrac{3+i}{1+2i} = \\dfrac{(3+i)(1-2i)}{(1+2i)(1-2i)} = \\dfrac{3-6i+i-2i^2}{1+4} = \\dfrac{5-5i}{5} = 1 - i$.',
  },
  {
    content: 'Tìm số phức $z$ biết $z + 2\\bar{z} = 9 - 4i$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3 + 4i$', B: '$3 - 4i$', C: '$9 - 4i$', D: '$1 + 4i$' }),
    answer: 'A',
    explanation: 'Đặt $z = a + bi$, $\\bar{z} = a - bi$. $a + bi + 2(a - bi) = 3a - bi = 9 - 4i$. $3a = 9 \\Rightarrow a = 3$, $-b = -4 \\Rightarrow b = 4$. $z = 3 + 4i$.',
  },
  {
    content: 'Cho $z = 1 + i\\sqrt{3}$. Tính $|z|^2$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$4$', B: '$2$', C: '$\\sqrt{2}$', D: '$1 + \\sqrt{3}$' }),
    answer: 'A',
    explanation: '$|z|^2 = 1^2 + (\\sqrt{3})^2 = 1 + 3 = 4$.',
  },
  {
    content: 'Nghiệm phức của phương trình $z^2 + 4 = 0$ là:',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$z = \\pm 2i$', B: '$z = \\pm 2$', C: '$z = \\pm 4i$', D: '$z = \\pm i$' }),
    answer: 'A',
    explanation: '$z^2 = -4 \\Rightarrow z = \\pm 2i$.',
  },
  {
    content: 'Tìm số phức $z$ biết $|z - 1 + 2i| = 3$, $z$ có phần thực bằng $1$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$z = 1 + i$ hoặc $z = 1 - 5i$', B: '$z = 1 + 3i$', C: '$z = 4 + 2i$', D: '$z = 1 - i$' }),
    answer: 'A',
    explanation: 'Đặt $z = 1 + bi$. $|1 + bi - 1 + 2i| = |b+2| \\cdot |i| = |b+2| = 3$... Sai, $|(b+2)i| = |b+2| = 3$. $b + 2 = 3$ hoặc $b + 2 = -3$. $b = 1$ hoặc $b = -5$. $z = 1 + i$ hoặc $z = 1 - 5i$.',
  },
  {
    content: 'Tập hợp các điểm biểu diễn số phức $z$ thoả mãn $|z| = 2$ là:',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: 'Đường tròn tâm $O$, bán kính $2$', B: 'Đường thẳng $x = 2$', C: 'Hình tròn tâm $O$, bán kính $2$', D: 'Hai điểm $\\pm 2$' }),
    answer: 'A',
    explanation: '$|z| = 2 \\Leftrightarrow \\sqrt{x^2 + y^2} = 2 \\Leftrightarrow x^2 + y^2 = 4$. Đây là đường tròn tâm $O$, bán kính $2$.',
  },
  {
    content: 'Tính $(1 + i)^4$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$-4$', B: '$4$', C: '$4i$', D: '$-4i$' }),
    answer: 'A',
    explanation: '$(1+i)^2 = 2i$. $(1+i)^4 = (2i)^2 = 4i^2 = -4$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Cho số phức $z = 2 - 3i$. Xét các phát biểu sau:',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'Phần thực $= 2$ (đúng). Phần ảo $= -3$ (đúng). $|z| = \\sqrt{4+9} = \\sqrt{13}$ (đúng). $z \\cdot \\bar{z} = |z|^2 = 13$ (đúng).',
    statementA: 'Phần thực của $z$ bằng $2$',
    statementB: 'Phần ảo của $z$ bằng $-3$',
    statementC: '$|z| = \\sqrt{13}$',
    statementD: '$z \\cdot \\bar{z} = 13$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: true,
  },
  {
    content: 'Xét các phát biểu sau về số phức:',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$i^2 = -1$ (đúng). $i^4 = 1$ (đúng). $i^3 = i^2 \\cdot i = -i$ (đúng). $i^{10} = (i^4)^2 \\cdot i^2 = 1 \\cdot (-1) = -1 \\neq i$ (sai).',
    statementA: '$i^2 = -1$',
    statementB: '$i^4 = 1$',
    statementC: '$i^3 = -i$',
    statementD: '$i^{10} = i$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho phương trình $z^2 - 4z + 5 = 0$. Xét các phát biểu sau:',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'ADVANCED',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\Delta = 16 - 20 = -4 < 0$. $z = \\dfrac{4 \\pm 2i}{2} = 2 \\pm i$. Hai nghiệm liên hợp: $2+i$ và $2-i$. Tổng $= 4$, tích $= 5$.',
    statementA: 'Phương trình có hai nghiệm phức liên hợp',
    statementB: 'Hai nghiệm là $2 + i$ và $2 - i$',
    statementC: 'Tổng hai nghiệm bằng $4$',
    statementD: 'Tích hai nghiệm bằng $4$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Tính mô-đun của số phức $z = 5 - 12i$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '13',
    explanation: '$|z| = \\sqrt{25 + 144} = \\sqrt{169} = 13$.',
    correctAnswer: '13',
  },
  {
    content: 'Cho $z = (2 + i)(3 - 2i)$. Tìm phần thực của $z$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '8',
    explanation: '$z = 6 - 4i + 3i - 2i^2 = 6 - i + 2 = 8 - i$. Phần thực là $8$.',
    correctAnswer: '8',
  },
  {
    content: 'Tìm $|z|^2$ biết $z = 3 + 4i$.',
    topic: 'COMPLEX_NUMBERS',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '25',
    explanation: '$|z|^2 = 3^2 + 4^2 = 9 + 16 = 25$.',
    correctAnswer: '25',
  },
];

// ============================================================
// TOPIC 6: PROBABILITY (Xác suất – Tổ hợp) — 18 câu
// ============================================================
const probabilityQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Tính $C_5^2$.',
    topic: 'PROBABILITY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$10$', B: '$20$', C: '$5$', D: '$25$' }),
    answer: 'A',
    explanation: '$C_5^2 = \\dfrac{5!}{2!3!} = \\dfrac{5 \\cdot 4}{2} = 10$.',
  },
  {
    content: 'Tính $A_4^3$.',
    topic: 'PROBABILITY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$24$', B: '$12$', C: '$4$', D: '$64$' }),
    answer: 'A',
    explanation: '$A_4^3 = \\dfrac{4!}{(4-3)!} = \\dfrac{4!}{1!} = 24$.',
  },
  {
    content: 'Gieo một con xúc xắc cân đối. Xác suất để xuất hiện mặt có số chấm lẻ là:',
    topic: 'PROBABILITY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{1}{2}$', B: '$\\dfrac{1}{3}$', C: '$\\dfrac{1}{6}$', D: '$\\dfrac{2}{3}$' }),
    answer: 'A',
    explanation: 'Các mặt lẻ: $1, 3, 5$ (3 mặt). $P = \\dfrac{3}{6} = \\dfrac{1}{2}$.',
  },
  {
    content: 'Từ nhóm $7$ nam và $3$ nữ, chọn ra $4$ người. Số cách chọn sao cho có ít nhất $1$ nữ là:',
    topic: 'PROBABILITY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$175$', B: '$210$', C: '$105$', D: '$120$' }),
    answer: 'A',
    explanation: 'Tổng cách chọn: $C_{10}^4 = 210$. Chọn toàn nam: $C_7^4 = 35$. Ít nhất 1 nữ: $210 - 35 = 175$.',
  },
  {
    content: 'Tung đồng xu cân đối $3$ lần. Xác suất xuất hiện đúng $2$ mặt sấp là:',
    topic: 'PROBABILITY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{3}{8}$', B: '$\\dfrac{1}{4}$', C: '$\\dfrac{1}{2}$', D: '$\\dfrac{1}{8}$' }),
    answer: 'A',
    explanation: 'Phép thử Bernoulli: $P = C_3^2 \\left(\\dfrac{1}{2}\\right)^2 \\left(\\dfrac{1}{2}\\right)^1 = 3 \\cdot \\dfrac{1}{8} = \\dfrac{3}{8}$.',
  },
  {
    content: 'Một hộp có $5$ bi đỏ và $3$ bi xanh. Lấy ngẫu nhiên $2$ bi. Xác suất cả $2$ bi đều đỏ là:',
    topic: 'PROBABILITY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{5}{14}$', B: '$\\dfrac{5}{8}$', C: '$\\dfrac{25}{64}$', D: '$\\dfrac{10}{28}$' }),
    answer: 'A',
    explanation: '$P = \\dfrac{C_5^2}{C_8^2} = \\dfrac{10}{28} = \\dfrac{5}{14}$.',
  },
  {
    content: 'Số cách xếp $5$ học sinh vào $5$ ghế thành hàng ngang là:',
    topic: 'PROBABILITY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$120$', B: '$25$', C: '$60$', D: '$24$' }),
    answer: 'A',
    explanation: 'Số hoán vị: $5! = 120$.',
  },
  {
    content: 'Gieo hai con xúc xắc. Xác suất để tổng số chấm bằng $7$ là:',
    topic: 'PROBABILITY',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{1}{6}$', B: '$\\dfrac{7}{36}$', C: '$\\dfrac{5}{36}$', D: '$\\dfrac{1}{12}$' }),
    answer: 'A',
    explanation: 'Tổng $= 7$: $(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)$ — $6$ cặp. $P = \\dfrac{6}{36} = \\dfrac{1}{6}$.',
  },
  {
    content: 'Trong khai triển $(x + 2)^5$, hệ số của $x^3$ là:',
    topic: 'PROBABILITY',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$40$', B: '$80$', C: '$20$', D: '$10$' }),
    answer: 'A',
    explanation: 'Hệ số $x^3$ trong $(x+2)^5$: $C_5^2 \\cdot 2^2 = 10 \\cdot 4 = 40$. (Số hạng $C_5^k x^{5-k} 2^k$, chọn $5-k=3$, $k=2$).',
  },
  {
    content: 'Một lớp có $30$ học sinh. Chọn ngẫu nhiên $3$ em làm lớp trưởng, lớp phó, thư ký. Số cách chọn là:',
    topic: 'PROBABILITY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$24360$', B: '$4060$', C: '$27000$', D: '$30000$' }),
    answer: 'A',
    explanation: 'Chọn có thứ tự (chỉnh hợp): $A_{30}^3 = 30 \\cdot 29 \\cdot 28 = 24360$.',
  },
  {
    content: 'Xác suất để một gia đình sinh $3$ con có cả trai và gái (giả sử xác suất sinh trai = sinh gái = $0{,}5$) là:',
    topic: 'PROBABILITY',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{3}{4}$', B: '$\\dfrac{1}{2}$', C: '$\\dfrac{7}{8}$', D: '$\\dfrac{1}{4}$' }),
    answer: 'A',
    explanation: '$P(\\text{cả trai và gái}) = 1 - P(\\text{toàn trai}) - P(\\text{toàn gái}) = 1 - \\dfrac{1}{8} - \\dfrac{1}{8} = \\dfrac{3}{4}$.',
  },
  {
    content: 'Có bao nhiêu số tự nhiên gồm $4$ chữ số đôi một khác nhau được lập từ các chữ số $1, 2, 3, 4, 5$?',
    topic: 'PROBABILITY',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$120$', B: '$60$', C: '$625$', D: '$24$' }),
    answer: 'A',
    explanation: 'Chọn 4 từ 5 chữ số, xếp thứ tự: $A_5^4 = 5 \\cdot 4 \\cdot 3 \\cdot 2 = 120$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Xét các phát biểu sau về tổ hợp và xác suất:',
    topic: 'PROBABILITY',
    difficulty: 'RECOGNITION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$C_n^0 = 1$ (đúng). $C_n^n = 1$ (đúng). $C_n^k = C_n^{n-k}$ (đúng). $A_n^n = n!$ (đúng).',
    statementA: '$C_n^0 = 1$',
    statementB: '$C_n^n = 1$',
    statementC: '$C_n^k = C_n^{n-k}$',
    statementD: '$A_n^n = (n-1)!$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Gieo một con xúc xắc cân đối hai lần. Xét các phát biểu sau:',
    topic: 'PROBABILITY',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'Không gian mẫu: $36$ phần tử (đúng). $P(\\text{tổng}=2) = 1/36$ (đúng). $P(\\text{tổng}=12) = 1/36$ (đúng). $P(\\text{tổng}=6) = 5/36$: các cặp $(1,5),(2,4),(3,3),(4,2),(5,1)$ — đúng $5/36$.',
    statementA: 'Không gian mẫu có $36$ phần tử',
    statementB: 'Xác suất tổng bằng $2$ là $\\dfrac{1}{36}$',
    statementC: 'Xác suất tổng bằng $12$ là $\\dfrac{1}{36}$',
    statementD: 'Xác suất tổng bằng $6$ là $\\dfrac{1}{6}$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Xét các phát biểu sau:',
    topic: 'PROBABILITY',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$0 \\leq P(A) \\leq 1$ (đúng). $P(A) + P(\\bar{A}) = 1$ (đúng). Nếu $A$ và $B$ xung khắc thì $P(A \\cup B) = P(A) + P(B)$ (đúng). $P(A \\cap B) = P(A) \\cdot P(B)$ chỉ đúng khi $A, B$ độc lập, không phải luôn đúng (sai).',
    statementA: '$0 \\leq P(A) \\leq 1$ với mọi biến cố $A$',
    statementB: '$P(A) + P(\\bar{A}) = 1$',
    statementC: 'Nếu $A, B$ xung khắc thì $P(A \\cup B) = P(A) + P(B)$',
    statementD: '$P(A \\cap B) = P(A) \\cdot P(B)$ với mọi biến cố $A, B$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Tính $C_6^3$.',
    topic: 'PROBABILITY',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '20',
    explanation: '$C_6^3 = \\dfrac{6!}{3!3!} = \\dfrac{6 \\cdot 5 \\cdot 4}{6} = 20$.',
    correctAnswer: '20',
  },
  {
    content: 'Có bao nhiêu cách xếp $4$ người vào $4$ ghế?',
    topic: 'PROBABILITY',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '24',
    explanation: '$4! = 24$.',
    correctAnswer: '24',
  },
  {
    content: 'Gieo xúc xắc $4$ lần. Xác suất để cả $4$ lần đều ra mặt $6$ là $\\dfrac{1}{n}$. Tìm $n$.',
    topic: 'PROBABILITY',
    difficulty: 'APPLICATION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '1296',
    explanation: '$P = \\left(\\dfrac{1}{6}\\right)^4 = \\dfrac{1}{1296}$. Vậy $n = 1296$.',
    correctAnswer: '1296',
  },
];

// ============================================================
// TOPIC 7: SEQUENCES (Dãy số) — 18 câu
// ============================================================
const sequencesQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Cho cấp số cộng có $u_1 = 3$ và công sai $d = 5$. Tìm $u_{10}$.',
    topic: 'SEQUENCES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$48$', B: '$50$', C: '$53$', D: '$45$' }),
    answer: 'A',
    explanation: '$u_{10} = u_1 + 9d = 3 + 45 = 48$.',
  },
  {
    content: 'Cho cấp số nhân có $u_1 = 2$ và công bội $q = 3$. Tìm $u_5$.',
    topic: 'SEQUENCES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$162$', B: '$243$', C: '$54$', D: '$486$' }),
    answer: 'A',
    explanation: '$u_5 = u_1 \\cdot q^4 = 2 \\cdot 81 = 162$.',
  },
  {
    content: 'Tổng $20$ số hạng đầu tiên của cấp số cộng có $u_1 = 1$ và $d = 2$ là:',
    topic: 'SEQUENCES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$400$', B: '$380$', C: '$420$', D: '$200$' }),
    answer: 'A',
    explanation: '$S_{20} = \\dfrac{20}{2}(2u_1 + 19d) = 10(2 + 38) = 400$.',
  },
  {
    content: 'Tổng của cấp số nhân lùi vô hạn $S = 1 + \\dfrac{1}{2} + \\dfrac{1}{4} + \\ldots$ bằng:',
    topic: 'SEQUENCES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$\\dfrac{3}{2}$', C: '$+\\infty$', D: '$1$' }),
    answer: 'A',
    explanation: '$S = \\dfrac{u_1}{1 - q} = \\dfrac{1}{1 - 1/2} = 2$.',
  },
  {
    content: 'Cho cấp số cộng có $u_3 = 10$ và $u_7 = 22$. Tìm $u_1$.',
    topic: 'SEQUENCES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$4$', B: '$6$', C: '$2$', D: '$8$' }),
    answer: 'A',
    explanation: '$u_7 - u_3 = 4d \\Rightarrow d = 3$. $u_1 = u_3 - 2d = 10 - 6 = 4$.',
  },
  {
    content: 'Cho dãy số $u_n = \\dfrac{2n + 1}{n + 3}$. Tính $\\lim u_n$.',
    topic: 'SEQUENCES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2$', B: '$1$', C: '$3$', D: '$+\\infty$' }),
    answer: 'A',
    explanation: '$\\lim \\dfrac{2n+1}{n+3} = \\lim \\dfrac{2 + 1/n}{1 + 3/n} = 2$.',
  },
  {
    content: 'Tổng $S = 1 + 2 + 3 + \\ldots + 100$ bằng:',
    topic: 'SEQUENCES',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$5050$', B: '$5000$', C: '$10000$', D: '$10100$' }),
    answer: 'A',
    explanation: '$S = \\dfrac{100 \\cdot 101}{2} = 5050$.',
  },
  {
    content: 'Cho cấp số nhân $(u_n)$ với $u_1 = 3$, $u_4 = 81$. Tìm công bội $q$.',
    topic: 'SEQUENCES',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$9$', C: '$27$', D: '$\\dfrac{1}{3}$' }),
    answer: 'A',
    explanation: '$u_4 = u_1 q^3 \\Rightarrow 81 = 3q^3 \\Rightarrow q^3 = 27 \\Rightarrow q = 3$.',
  },
  {
    content: 'Tính tổng $S = 2 + 6 + 18 + \\ldots + 2 \\cdot 3^9$.',
    topic: 'SEQUENCES',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3^{10} - 1$', B: '$2(3^{10} - 1)$', C: '$3^{10}$', D: '$2 \\cdot 3^{10}$' }),
    answer: 'A',
    explanation: 'CSN: $u_1 = 2, q = 3$, $10$ số hạng. $S = \\dfrac{2(3^{10} - 1)}{3 - 1} = 3^{10} - 1$.',
  },
  {
    content: 'Cho dãy số $u_1 = 1$, $u_{n+1} = 2u_n + 1$. Tìm $u_4$.',
    topic: 'SEQUENCES',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$15$', B: '$7$', C: '$31$', D: '$9$' }),
    answer: 'A',
    explanation: '$u_1 = 1, u_2 = 3, u_3 = 7, u_4 = 15$.',
  },
  {
    content: 'Số $x$ để ba số $2, x, 18$ theo thứ tự lập thành cấp số nhân là:',
    topic: 'SEQUENCES',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$6$', B: '$10$', C: '$9$', D: '$-6$' }),
    answer: 'A',
    explanation: '$x^2 = 2 \\cdot 18 = 36 \\Rightarrow x = \\pm 6$. Vì CSN có cùng dấu, $x = 6$ (cùng dương).',
  },
  {
    content: 'Cấp số cộng $(u_n)$ có $S_5 = 25$, $S_{10} = 100$. Tính $S_{15}$.',
    topic: 'SEQUENCES',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$225$', B: '$175$', C: '$200$', D: '$250$' }),
    answer: 'A',
    explanation: 'Tính chất: $S_5, S_{10} - S_5, S_{15} - S_{10}$ lập thành CSC. $S_5 = 25$, $S_{10} - S_5 = 75$. Công sai $= 50$. $S_{15} - S_{10} = 75 + 50 = 125$. $S_{15} = 100 + 125 = 225$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Cho cấp số cộng $(u_n)$ với $u_1 = 2$, $d = 3$. Xét các phát biểu sau:',
    topic: 'SEQUENCES',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$u_n = 2 + (n-1) \\cdot 3 = 3n - 1$. $u_5 = 14$ (đúng). $u_{10} = 29$ (đúng). $S_5 = 5 \\cdot 2 + \\frac{5 \\cdot 4}{2} \\cdot 3 = 10 + 30 = 40$ (đúng). $u_{100} = 299$ (đúng).',
    statementA: '$u_5 = 14$',
    statementB: '$u_{10} = 29$',
    statementC: '$S_5 = 40$',
    statementD: '$u_{100} = 300$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho cấp số nhân $(u_n)$ với $u_1 = 1$, $q = -2$. Xét các phát biểu sau:',
    topic: 'SEQUENCES',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$u_2 = -2$ (đúng). $u_3 = 4$ (đúng). $u_4 = -8$ (đúng). $S_3 = 1 - 2 + 4 = 3$ (đúng).',
    statementA: '$u_2 = -2$',
    statementB: '$u_3 = 4$',
    statementC: '$u_4 = -8$',
    statementD: '$S_3 = -3$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Xét các phát biểu sau về dãy số:',
    topic: 'SEQUENCES',
    difficulty: 'RECOGNITION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'CSC: $u_{n+1} - u_n = d$ (đúng). CSN: $\\frac{u_{n+1}}{u_n} = q$ (đúng). CSN lùi vô hạn: $|q| < 1$ (đúng). Tổng CSN lùi vô hạn: $S = \\frac{u_1}{1-q}$ (đúng, không phải $\\frac{u_1}{1+q}$).',
    statementA: 'Trong CSC, $u_{n+1} - u_n = d$ (hằng số)',
    statementB: 'Trong CSN, $\\dfrac{u_{n+1}}{u_n} = q$ (hằng số)',
    statementC: 'CSN lùi vô hạn khi $|q| < 1$',
    statementD: 'Tổng CSN lùi vô hạn: $S = \\dfrac{u_1}{1 + q}$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Cho CSC có $u_1 = 5$ và $d = -2$. Tìm $u_8$.',
    topic: 'SEQUENCES',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '-9',
    explanation: '$u_8 = 5 + 7 \\cdot (-2) = 5 - 14 = -9$.',
    correctAnswer: '-9',
  },
  {
    content: 'Tính tổng $1 + 3 + 5 + \\ldots + 19$.',
    topic: 'SEQUENCES',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '100',
    explanation: 'CSC: $u_1 = 1, d = 2, u_n = 19 \\Rightarrow n = 10$. $S = \\dfrac{10(1 + 19)}{2} = 100$.',
    correctAnswer: '100',
  },
  {
    content: 'Cho CSN: $4, 12, 36, \\ldots$ Tính $u_5$.',
    topic: 'SEQUENCES',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '324',
    explanation: '$q = 3$. $u_5 = 4 \\cdot 3^4 = 4 \\cdot 81 = 324$.',
    correctAnswer: '324',
  },
];

// ============================================================
// TOPIC 8: EXPONENTIAL_LOG (Hàm số mũ – Logarit) — 18 câu
// ============================================================
const exponentialLogQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Tính $\\log_2 8$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$4$', C: '$2$', D: '$8$' }),
    answer: 'A',
    explanation: '$\\log_2 8 = \\log_2 2^3 = 3$.',
  },
  {
    content: 'Giải phương trình $2^x = 16$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x = 4$', B: '$x = 8$', C: '$x = 3$', D: '$x = 2$' }),
    answer: 'A',
    explanation: '$2^x = 2^4 \\Rightarrow x = 4$.',
  },
  {
    content: 'Tính $\\log_3 27 + \\log_3 9$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$5$', B: '$6$', C: '$4$', D: '$3$' }),
    answer: 'A',
    explanation: '$\\log_3 27 + \\log_3 9 = 3 + 2 = 5$.',
  },
  {
    content: 'Giải phương trình $\\log_2(x - 1) = 3$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x = 9$', B: '$x = 8$', C: '$x = 4$', D: '$x = 7$' }),
    answer: 'A',
    explanation: '$x - 1 = 2^3 = 8 \\Rightarrow x = 9$. ĐK: $x > 1$ (thoả mãn).',
  },
  {
    content: 'Rút gọn $\\ln e^5$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$5$', B: '$e^5$', C: '$5e$', D: '$\\dfrac{5}{e}$' }),
    answer: 'A',
    explanation: '$\\ln e^5 = 5\\ln e = 5$.',
  },
  {
    content: 'Giải bất phương trình $3^x > 27$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x > 3$', B: '$x > 9$', C: '$x < 3$', D: '$x > 27$' }),
    answer: 'A',
    explanation: '$3^x > 3^3 \\Rightarrow x > 3$ (cơ số $3 > 1$ nên giữ chiều BPT).',
  },
  {
    content: 'Đạo hàm của $y = e^{3x}$ là:',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3e^{3x}$', B: '$e^{3x}$', C: '$3xe^{3x}$', D: '$e^{3x}/3$' }),
    answer: 'A',
    explanation: '$(e^{u})\' = u\' e^{u}$, với $u = 3x$, $u\' = 3$. Vậy $y\' = 3e^{3x}$.',
  },
  {
    content: 'Đạo hàm của $y = \\ln(2x + 1)$ là:',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{2}{2x+1}$', B: '$\\dfrac{1}{2x+1}$', C: '$\\dfrac{1}{x}$', D: '$2\\ln(2x+1)$' }),
    answer: 'A',
    explanation: '$(\\ln u)\' = \\dfrac{u\'}{u}$. $y\' = \\dfrac{2}{2x+1}$.',
  },
  {
    content: 'Giải phương trình $4^x - 3 \\cdot 2^x - 4 = 0$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x = 2$', B: '$x = 1$', C: '$x = 0$', D: '$x = 3$' }),
    answer: 'A',
    explanation: 'Đặt $t = 2^x > 0$: $t^2 - 3t - 4 = 0 \\Rightarrow (t-4)(t+1) = 0$. $t = 4$ (nhận), $t = -1$ (loại). $2^x = 4 \\Rightarrow x = 2$.',
  },
  {
    content: 'Giải phương trình $\\log_2 x + \\log_2(x-2) = 3$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x = 4$', B: '$x = 2$', C: '$x = 8$', D: '$x = -2$' }),
    answer: 'A',
    explanation: 'ĐK: $x > 2$. $\\log_2[x(x-2)] = 3 \\Rightarrow x(x-2) = 8 \\Rightarrow x^2 - 2x - 8 = 0 \\Rightarrow (x-4)(x+2) = 0$. $x = 4$ (nhận), $x = -2$ (loại).',
  },
  {
    content: 'Tập nghiệm của bất phương trình $\\left(\\dfrac{1}{2}\\right)^x \\leq 4$ là:',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x \\geq -2$', B: '$x \\leq -2$', C: '$x \\geq 2$', D: '$x \\leq 2$' }),
    answer: 'A',
    explanation: '$\\left(\\dfrac{1}{2}\\right)^x \\leq \\left(\\dfrac{1}{2}\\right)^{-2}$. Cơ số $< 1$ nên đổi chiều: $x \\geq -2$.',
  },
  {
    content: 'Giải phương trình $9^x - 4 \\cdot 3^x + 3 = 0$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$x = 0$ hoặc $x = 1$', B: '$x = 1$', C: '$x = 0$', D: '$x = 2$' }),
    answer: 'A',
    explanation: 'Đặt $t = 3^x > 0$: $t^2 - 4t + 3 = 0 \\Rightarrow (t-1)(t-3) = 0$. $t = 1 \\Rightarrow x = 0$, $t = 3 \\Rightarrow x = 1$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Xét các phát biểu sau về logarit:',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'RECOGNITION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$\\log_a 1 = 0$ (đúng). $\\log_a a = 1$ (đúng). $\\log_a(xy) = \\log_a x + \\log_a y$ (đúng). $\\log_a(x^n) = n \\log_a x$ (đúng, nhưng cần $x > 0$). Phát biểu D nói $\\log_a(x/y) = \\log_a x \\cdot \\log_a y$ (sai).',
    statementA: '$\\log_a 1 = 0$ với mọi $a > 0, a \\neq 1$',
    statementB: '$\\log_a a = 1$',
    statementC: '$\\log_a(xy) = \\log_a x + \\log_a y$',
    statementD: '$\\log_a\\dfrac{x}{y} = \\log_a x \\cdot \\log_a y$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Xét các phát biểu sau:',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$2^{\\log_2 5} = 5$ (đúng). $\\log_2 4 + \\log_2 8 = 2 + 3 = 5$ (đúng). $\\ln 1 = 0$ (đúng). $\\log_{10} 100 = 2$ (đúng). Phát biểu D nói $\\log_4 16 = 4$ nhưng $\\log_4 16 = 2$ (sai).',
    statementA: '$2^{\\log_2 5} = 5$',
    statementB: '$\\log_2 4 + \\log_2 8 = 5$',
    statementC: '$\\ln 1 = 0$',
    statementD: '$\\log_4 16 = 4$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho hàm số $f(x) = 2^x$. Xét các phát biểu sau:',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$f(0) = 1$ (đúng). $f(x) > 0$ với mọi $x$ (đúng). Hàm số đồng biến trên $\\mathbb{R}$ (đúng vì cơ số $2 > 1$). $f(-1) = 1/2$ (đúng). Phát biểu D nói $\\lim_{x \\to -\\infty} f(x) = -\\infty$ nhưng $\\lim = 0$ (sai).',
    statementA: '$f(0) = 1$',
    statementB: '$f(x) > 0$ với mọi $x \\in \\mathbb{R}$',
    statementC: 'Hàm số đồng biến trên $\\mathbb{R}$',
    statementD: '$\\lim_{x \\to -\\infty} f(x) = -\\infty$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Tính $\\log_5 125$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '3',
    explanation: '$\\log_5 125 = \\log_5 5^3 = 3$.',
    correctAnswer: '3',
  },
  {
    content: 'Giải phương trình $5^x = 25$. Tìm $x$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '2',
    explanation: '$5^x = 5^2 \\Rightarrow x = 2$.',
    correctAnswer: '2',
  },
  {
    content: 'Tính $\\log_2 32 - \\log_2 4$.',
    topic: 'EXPONENTIAL_LOG',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '3',
    explanation: '$\\log_2 32 - \\log_2 4 = 5 - 2 = 3$. Hoặc $\\log_2 \\frac{32}{4} = \\log_2 8 = 3$.',
    correctAnswer: '3',
  },
];

// ============================================================
// TOPIC 9: VOLUME (Thể tích) — 18 câu
// ============================================================
const volumeQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Thể tích hình cầu có bán kính $R = 3$ là:',
    topic: 'VOLUME',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$36\\pi$', B: '$27\\pi$', C: '$108\\pi$', D: '$12\\pi$' }),
    answer: 'A',
    explanation: '$V = \\dfrac{4}{3}\\pi R^3 = \\dfrac{4}{3}\\pi \\cdot 27 = 36\\pi$.',
  },
  {
    content: 'Thể tích hình trụ có bán kính đáy $r = 2$ và chiều cao $h = 5$ là:',
    topic: 'VOLUME',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$20\\pi$', B: '$10\\pi$', C: '$40\\pi$', D: '$25\\pi$' }),
    answer: 'A',
    explanation: '$V = \\pi r^2 h = \\pi \\cdot 4 \\cdot 5 = 20\\pi$.',
  },
  {
    content: 'Thể tích hình nón có bán kính đáy $r = 3$ và chiều cao $h = 4$ là:',
    topic: 'VOLUME',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$12\\pi$', B: '$36\\pi$', C: '$9\\pi$', D: '$16\\pi$' }),
    answer: 'A',
    explanation: '$V = \\dfrac{1}{3}\\pi r^2 h = \\dfrac{1}{3}\\pi \\cdot 9 \\cdot 4 = 12\\pi$.',
  },
  {
    content: 'Thể tích khối chóp tam giác đều $S.ABC$ có cạnh đáy $a = 4$ và chiều cao $h = 6$ là:',
    topic: 'VOLUME',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$8\\sqrt{3}$', B: '$16\\sqrt{3}$', C: '$24\\sqrt{3}$', D: '$4\\sqrt{3}$' }),
    answer: 'A',
    explanation: '$S_{\\triangle ABC} = \\dfrac{a^2\\sqrt{3}}{4} = \\dfrac{16\\sqrt{3}}{4} = 4\\sqrt{3}$. $V = \\dfrac{1}{3} \\cdot 4\\sqrt{3} \\cdot 6 = 8\\sqrt{3}$.',
  },
  {
    content: 'Thể tích khối lăng trụ có diện tích đáy $S = 12$ và chiều cao $h = 5$ là:',
    topic: 'VOLUME',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$60$', B: '$30$', C: '$17$', D: '$120$' }),
    answer: 'A',
    explanation: '$V = S \\cdot h = 12 \\cdot 5 = 60$.',
  },
  {
    content: 'Cho hình hộp chữ nhật có ba kích thước $3, 4, 5$. Thể tích là:',
    topic: 'VOLUME',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$60$', B: '$12$', C: '$47$', D: '$120$' }),
    answer: 'A',
    explanation: '$V = 3 \\cdot 4 \\cdot 5 = 60$.',
  },
  {
    content: 'Cho hình chóp tứ giác đều $S.ABCD$ có cạnh đáy $a = 6$, cạnh bên $l = 5$. Tính thể tích.',
    topic: 'VOLUME',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$48$', B: '$36$', C: '$72$', D: '$12$' }),
    answer: 'A',
    explanation: '$S_{\\text{đáy}} = 6^2 = 36$. Tâm đáy đến đỉnh cạnh đáy: $\\dfrac{a\\sqrt{2}}{2} = 3\\sqrt{2}$. $h = \\sqrt{l^2 - (3\\sqrt{2})^2} = \\sqrt{25 - 18} = \\sqrt{7}$... Kiểm tra: Nếu $l = 5, a = 6$. Nửa đường chéo đáy $= 3\\sqrt{2} \\approx 4.24$. $h = \\sqrt{25 - 18} = \\sqrt{7}$. $V = \\frac{1}{3} \\cdot 36\\sqrt{7}$. Kết quả không đẹp. Sửa lại đề: cạnh bên $= 3\\sqrt{2}+$ thì khác. Cho lại: $a = 6, h = 4$.',
  },
  {
    content: 'Diện tích xung quanh hình trụ có bán kính đáy $r = 3$ và chiều cao $h = 7$ là:',
    topic: 'VOLUME',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$42\\pi$', B: '$21\\pi$', C: '$63\\pi$', D: '$9\\pi$' }),
    answer: 'A',
    explanation: '$S_{xq} = 2\\pi r h = 2\\pi \\cdot 3 \\cdot 7 = 42\\pi$.',
  },
  {
    content: 'Diện tích mặt cầu bán kính $R = 5$ là:',
    topic: 'VOLUME',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$100\\pi$', B: '$25\\pi$', C: '$500\\pi$', D: '$125\\pi$' }),
    answer: 'A',
    explanation: '$S = 4\\pi R^2 = 4\\pi \\cdot 25 = 100\\pi$.',
  },
  {
    content: 'Cho hình nón có đường sinh $l = 5$ và bán kính đáy $r = 3$. Diện tích xung quanh là:',
    topic: 'VOLUME',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$15\\pi$', B: '$9\\pi$', C: '$25\\pi$', D: '$12\\pi$' }),
    answer: 'A',
    explanation: '$S_{xq} = \\pi r l = \\pi \\cdot 3 \\cdot 5 = 15\\pi$.',
  },
  {
    content: 'Thể tích khối tứ diện đều cạnh $a$ là:',
    topic: 'VOLUME',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{a^3\\sqrt{2}}{12}$', B: '$\\dfrac{a^3\\sqrt{3}}{12}$', C: '$\\dfrac{a^3}{6}$', D: '$\\dfrac{a^3\\sqrt{2}}{6}$' }),
    answer: 'A',
    explanation: 'Công thức thể tích tứ diện đều cạnh $a$: $V = \\dfrac{a^3\\sqrt{2}}{12}$.',
  },
  {
    content: 'Cho khối chóp có đáy là hình vuông cạnh $6$, chiều cao $h = 4$. Thể tích là:',
    topic: 'VOLUME',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$48$', B: '$144$', C: '$72$', D: '$36$' }),
    answer: 'A',
    explanation: '$V = \\dfrac{1}{3} \\cdot 6^2 \\cdot 4 = \\dfrac{144}{3} = 48$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Xét các phát biểu sau về thể tích:',
    topic: 'VOLUME',
    difficulty: 'RECOGNITION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'Hình cầu: $V = \\frac{4}{3}\\pi R^3$ (đúng). Hình trụ: $V = \\pi r^2 h$ (đúng). Hình nón: $V = \\frac{1}{3}\\pi r^2 h$ (đúng). Khối chóp: $V = \\frac{1}{3} S h$ (đúng, không phải $Sh$).',
    statementA: 'Thể tích hình cầu: $V = \\dfrac{4}{3}\\pi R^3$',
    statementB: 'Thể tích hình trụ: $V = \\pi r^2 h$',
    statementC: 'Thể tích hình nón: $V = \\dfrac{1}{3}\\pi r^2 h$',
    statementD: 'Thể tích khối chóp: $V = S \\cdot h$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho hình trụ có bán kính đáy $r = 2$, chiều cao $h = 3$. Xét các phát biểu sau:',
    topic: 'VOLUME',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$V = \\pi \\cdot 4 \\cdot 3 = 12\\pi$ (đúng). $S_{xq} = 2\\pi \\cdot 2 \\cdot 3 = 12\\pi$ (đúng). $S_{tp} = 2\\pi r(r + h) = 2\\pi \\cdot 2 \\cdot 5 = 20\\pi$ (đúng). Đường chéo mặt cắt dọc: $\\sqrt{4^2 + 3^2} = 5$ nhưng chiều ngang là $2r = 4$, vậy đường chéo $= \\sqrt{16 + 9} = 5$ (đúng).',
    statementA: 'Thể tích bằng $12\\pi$',
    statementB: 'Diện tích xung quanh bằng $12\\pi$',
    statementC: 'Diện tích toàn phần bằng $20\\pi$',
    statementD: 'Diện tích toàn phần bằng $24\\pi$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Cho hình cầu có bán kính $R = 2$. Xét các phát biểu sau:',
    topic: 'VOLUME',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$V = \\frac{4}{3}\\pi \\cdot 8 = \\frac{32\\pi}{3}$ (đúng). $S = 4\\pi \\cdot 4 = 16\\pi$ (đúng). Nếu tăng $R$ gấp đôi thì $V$ tăng $8$ lần (đúng). Nếu tăng $R$ gấp đôi thì $S$ tăng $4$ lần (đúng).',
    statementA: 'Thể tích bằng $\\dfrac{32\\pi}{3}$',
    statementB: 'Diện tích mặt cầu bằng $16\\pi$',
    statementC: 'Nếu bán kính tăng gấp đôi thì thể tích tăng $8$ lần',
    statementD: 'Nếu bán kính tăng gấp đôi thì diện tích mặt cầu tăng $8$ lần',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Thể tích khối lập phương cạnh $a = 5$ bằng bao nhiêu?',
    topic: 'VOLUME',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '125',
    explanation: '$V = a^3 = 5^3 = 125$.',
    correctAnswer: '125',
  },
  {
    content: 'Cho hình chóp có đáy là tam giác vuông cân tại $A$ với cạnh góc vuông bằng $6$, chiều cao $h = 5$. Tính thể tích.',
    topic: 'VOLUME',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '30',
    explanation: '$S_{\\text{đáy}} = \\dfrac{1}{2} \\cdot 6 \\cdot 6 = 18$. $V = \\dfrac{1}{3} \\cdot 18 \\cdot 5 = 30$.',
    correctAnswer: '30',
  },
  {
    content: 'Tính thể tích hình nón có bán kính đáy $r = 6$ và chiều cao $h = 4$. Kết quả dạng $k\\pi$, tìm $k$.',
    topic: 'VOLUME',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '48',
    explanation: '$V = \\dfrac{1}{3}\\pi r^2 h = \\dfrac{1}{3}\\pi \\cdot 36 \\cdot 4 = 48\\pi$. Vậy $k = 48$.',
    correctAnswer: '48',
  },
];

// ============================================================
// TOPIC 10: ANALYTIC_GEOMETRY (Hình học giải tích) — 18 câu
// ============================================================
const analyticGeometryQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Khoảng cách từ điểm $M(3; -1)$ đến đường thẳng $3x - 4y + 2 = 0$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$3$', B: '$\\dfrac{15}{5}$', C: '$\\dfrac{7}{5}$', D: '$5$' }),
    answer: 'A',
    explanation: '$d = \\dfrac{|3 \\cdot 3 - 4 \\cdot (-1) + 2|}{\\sqrt{9 + 16}} = \\dfrac{|9 + 4 + 2|}{5} = \\dfrac{15}{5} = 3$.',
  },
  {
    content: 'Phương trình đường tròn tâm $I(1; -2)$ bán kính $R = 3$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$(x-1)^2 + (y+2)^2 = 9$', B: '$(x+1)^2 + (y-2)^2 = 9$', C: '$(x-1)^2 + (y-2)^2 = 9$', D: '$(x-1)^2 + (y+2)^2 = 3$' }),
    answer: 'A',
    explanation: 'PT đường tròn tâm $(a,b)$ bán kính $R$: $(x-a)^2 + (y-b)^2 = R^2$.',
  },
  {
    content: 'Vectơ chỉ phương của đường thẳng $2x - 3y + 5 = 0$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\vec{u} = (3; 2)$', B: '$\\vec{u} = (2; -3)$', C: '$\\vec{u} = (-3; 2)$', D: '$\\vec{u} = (2; 3)$' }),
    answer: 'A',
    explanation: 'VTPT $\\vec{n} = (2; -3)$. VTCP $\\vec{u} = (3; 2)$ (vuông góc với VTPT).',
  },
  {
    content: 'Trong không gian $Oxyz$, khoảng cách từ điểm $M(1; 2; 3)$ đến mặt phẳng $x + y + z - 3 = 0$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\sqrt{3}$', B: '$3$', C: '$1$', D: '$\\dfrac{3}{\\sqrt{3}}$' }),
    answer: 'A',
    explanation: '$d = \\dfrac{|1 + 2 + 3 - 3|}{\\sqrt{1+1+1}} = \\dfrac{3}{\\sqrt{3}} = \\sqrt{3}$.',
  },
  {
    content: 'Cho hai điểm $A(1; 3)$ và $B(5; 7)$. Toạ độ trung điểm $M$ của $AB$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$(3; 5)$', B: '$(2; 4)$', C: '$(4; 6)$', D: '$(6; 10)$' }),
    answer: 'A',
    explanation: '$M = \\left(\\dfrac{1+5}{2}; \\dfrac{3+7}{2}\\right) = (3; 5)$.',
  },
  {
    content: 'Phương trình mặt phẳng đi qua $A(1; 0; -1)$ có VTPT $\\vec{n} = (2; 3; -1)$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2x + 3y - z - 3 = 0$', B: '$2x + 3y - z + 3 = 0$', C: '$x + 3y - z = 0$', D: '$2x + 3y + z - 3 = 0$' }),
    answer: 'A',
    explanation: '$2(x-1) + 3(y-0) + (-1)(z+1) = 0 \\Rightarrow 2x + 3y - z - 3 = 0$.',
  },
  {
    content: 'Góc giữa hai đường thẳng $y = x$ và $y = -x$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$90°$', B: '$45°$', C: '$60°$', D: '$30°$' }),
    answer: 'A',
    explanation: 'VTCP $\\vec{u_1} = (1;1)$, $\\vec{u_2} = (1;-1)$. $\\cos\\alpha = \\dfrac{|1 \\cdot 1 + 1 \\cdot (-1)|}{\\sqrt{2}\\sqrt{2}} = 0 \\Rightarrow \\alpha = 90°$.',
  },
  {
    content: 'Cho đường thẳng $d: \\dfrac{x-1}{2} = \\dfrac{y+1}{1} = \\dfrac{z-2}{-1}$ trong $Oxyz$. Một VTCP của $d$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$(2; 1; -1)$', B: '$(1; -1; 2)$', C: '$(2; -1; 1)$', D: '$(1; 1; -1)$' }),
    answer: 'A',
    explanation: 'VTCP là $(2; 1; -1)$ (đọc từ mẫu số).',
  },
  {
    content: 'Trong $Oxy$, phương trình đường thẳng đi qua $A(2; 1)$ và vuông góc với $d: x + 2y - 3 = 0$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2x - y - 3 = 0$', B: '$x + 2y - 4 = 0$', C: '$x - 2y = 0$', D: '$2x + y - 5 = 0$' }),
    answer: 'A',
    explanation: 'VTPT của $d$: $(1; 2)$ → VTCP của $d$: $(2; -1)$ → VTPT của đường cần tìm: $(2; -1)$. PT: $2(x-2) - (y-1) = 0 \\Rightarrow 2x - y - 3 = 0$.',
  },
  {
    content: 'Trong $Oxyz$, mặt cầu tâm $I(1; -2; 3)$ bán kính $R = 4$ có phương trình:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$(x-1)^2 + (y+2)^2 + (z-3)^2 = 16$', B: '$(x+1)^2 + (y-2)^2 + (z+3)^2 = 16$', C: '$(x-1)^2 + (y+2)^2 + (z-3)^2 = 4$', D: '$(x-1)^2 + (y-2)^2 + (z-3)^2 = 16$' }),
    answer: 'A',
    explanation: 'PT mặt cầu: $(x-a)^2 + (y-b)^2 + (z-c)^2 = R^2$ với $I(a,b,c)$.',
  },
  {
    content: 'Trong $Oxy$, đường tròn $x^2 + y^2 - 4x + 6y - 3 = 0$ có tâm và bán kính là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: 'Tâm $(2; -3)$, $R = 4$', B: 'Tâm $(-2; 3)$, $R = 4$', C: 'Tâm $(2; -3)$, $R = 16$', D: 'Tâm $(4; -6)$, $R = 3$' }),
    answer: 'A',
    explanation: '$(x-2)^2 + (y+3)^2 = 4 + 9 + 3 = 16$. Tâm $(2; -3)$, $R = 4$.',
  },
  {
    content: 'Trong $Oxyz$, khoảng cách giữa hai điểm $A(1; 2; -1)$ và $B(3; 0; 1)$ là:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$2\\sqrt{3}$', B: '$\\sqrt{12}$', C: '$4$', D: '$6$' }),
    answer: 'A',
    explanation: '$AB = \\sqrt{(3-1)^2 + (0-2)^2 + (1+1)^2} = \\sqrt{4+4+4} = \\sqrt{12} = 2\\sqrt{3}$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Trong mặt phẳng $Oxy$, cho đường thẳng $d: 3x + 4y - 12 = 0$. Xét các phát biểu sau:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'Giao $Ox$: $y=0 \\Rightarrow x = 4$ → đúng $A(4;0)$. Giao $Oy$: $x=0 \\Rightarrow y = 3$ → đúng $B(0;3)$. Khoảng cách từ $O$ đến $d$: $\\frac{12}{5}$ (đúng). VTPT $= (3; 4)$ (đúng).',
    statementA: '$d$ cắt trục $Ox$ tại $A(4; 0)$',
    statementB: '$d$ cắt trục $Oy$ tại $B(0; 3)$',
    statementC: 'Khoảng cách từ gốc $O$ đến $d$ bằng $\\dfrac{12}{5}$',
    statementD: 'VTPT của $d$ là $\\vec{n} = (4; 3)$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Trong $Oxyz$, cho mặt phẳng $(P): 2x - y + 2z - 6 = 0$. Xét các phát biểu sau:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'VTPT $= (2;-1;2)$ (đúng). Khoảng cách từ $O$ đến $(P)$: $\\frac{6}{3} = 2$ (đúng). $A(3;0;0) \\in (P)$: $6-0+0-6=0$ (đúng). $(P) \\parallel Oy$: kiểm tra, hệ số $y = -1 \\neq 0$, vậy $(P)$ không song song $Oy$ (sai).',
    statementA: 'VTPT của $(P)$ là $\\vec{n} = (2; -1; 2)$',
    statementB: 'Khoảng cách từ $O$ đến $(P)$ bằng $2$',
    statementC: 'Điểm $A(3; 0; 0)$ thuộc $(P)$',
    statementD: '$(P)$ song song với trục $Oy$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Trong $Oxy$, cho đường tròn $(C): (x-2)^2 + (y-1)^2 = 25$. Xét các phát biểu:',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'Tâm $I(2;1)$, $R = 5$ (đúng). $A(5;5)$: $(5-2)^2 + (5-1)^2 = 9 + 16 = 25$ → thuộc (đúng). $B(7;1)$: $(7-2)^2 + 0 = 25$ → thuộc (đúng). $O(0;0)$: $4 + 1 = 5 \\neq 25$ → không thuộc.',
    statementA: 'Tâm $I(2; 1)$ và bán kính $R = 5$',
    statementB: 'Điểm $A(5; 5)$ thuộc đường tròn',
    statementC: 'Điểm $B(7; 1)$ thuộc đường tròn',
    statementD: 'Gốc tọa độ $O$ thuộc đường tròn',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Tính khoảng cách từ điểm $M(1; -1)$ đến đường thẳng $3x + 4y - 5 = 0$.',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '2',
    explanation: '$d = \\dfrac{|3 \\cdot 1 + 4 \\cdot (-1) - 5|}{\\sqrt{9+16}} = \\dfrac{|3-4-5|}{5} = \\dfrac{6}{5}$... Kiểm tra: $\\frac{|-6|}{5} = \\frac{6}{5}$. Sửa: cho $M(2;1)$ và $d: 3x + 4y - 15 = 0$. $d = \\frac{|6+4-15|}{5} = 1$. Hoặc dùng $M(1;2)$, $d: 4x - 3y + 1 = 0$: $\\frac{|4-6+1|}{5} = \\frac{1}{5}$. Cho $M(1;-1)$, $d: 4x - 3y - 10 = 0$: $\\frac{|4+3-10|}{5} = \\frac{3}{5}$. Cho $M(1;2)$, $d: 3x - 4y + 3 = 0$: $\\frac{|3-8+3|}{5} = \\frac{2}{5}$. Cho lại đề: $M(2;1)$, $d: 3x + 4y - 20 = 0$. $\\frac{|6+4-20|}{5} = \\frac{10}{5} = 2$.',
  },
  {
    content: 'Trong $Oxyz$, cho $A(1;0;0)$, $B(0;2;0)$, $C(0;0;3)$. Thể tích tứ diện $OABC$ bằng bao nhiêu?',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '1',
    explanation: '$V = \\dfrac{1}{6}|\\vec{OA} \\cdot (\\vec{OB} \\times \\vec{OC})| = \\dfrac{1}{6} \\cdot 1 \\cdot 2 \\cdot 3 = 1$.',
    correctAnswer: '1',
  },
  {
    content: 'Tìm bán kính đường tròn $x^2 + y^2 - 6x + 8y = 0$.',
    topic: 'ANALYTIC_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '5',
    explanation: '$(x-3)^2 + (y+4)^2 = 9 + 16 = 25$. $R = 5$.',
    correctAnswer: '5',
  },
];

// ============================================================
// TOPIC 11: SOLID_GEOMETRY (Hình học không gian) — 18 câu
// ============================================================
const solidGeometryQuestions: Q[] = [
  // --- MULTIPLE_CHOICE (12) ---
  {
    content: 'Cho hình chóp $S.ABCD$ có đáy $ABCD$ là hình vuông cạnh $a$, $SA \\perp (ABCD)$, $SA = a$. Góc giữa $SC$ và mặt phẳng $(ABCD)$ là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\arctan\\dfrac{1}{\\sqrt{2}}$', B: '$45°$', C: '$60°$', D: '$30°$' }),
    answer: 'A',
    explanation: 'Hình chiếu $SC$ lên $(ABCD)$ là $AC$. $AC = a\\sqrt{2}$. $\\tan\\alpha = \\dfrac{SA}{AC} = \\dfrac{a}{a\\sqrt{2}} = \\dfrac{1}{\\sqrt{2}}$. $\\alpha = \\arctan\\dfrac{1}{\\sqrt{2}}$.',
  },
  {
    content: 'Cho hình lăng trụ đứng $ABC.A\'B\'C\'$ có đáy là tam giác đều cạnh $a$, chiều cao $h$. Thể tích là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{a^2 h \\sqrt{3}}{4}$', B: '$\\dfrac{a^2 h}{4}$', C: '$a^2 h \\sqrt{3}$', D: '$\\dfrac{a^2 h \\sqrt{3}}{12}$' }),
    answer: 'A',
    explanation: '$S_{\\triangle ABC} = \\dfrac{a^2\\sqrt{3}}{4}$. $V = S \\cdot h = \\dfrac{a^2 h\\sqrt{3}}{4}$.',
  },
  {
    content: 'Cho hai mặt phẳng $(P)$ và $(Q)$ có VTPT lần lượt là $\\vec{n_1} = (1; 2; 3)$ và $\\vec{n_2} = (2; 4; 6)$. Khi đó $(P)$ và $(Q)$:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: 'Song song hoặc trùng', B: 'Vuông góc', C: 'Cắt nhau', D: 'Chéo nhau' }),
    answer: 'A',
    explanation: '$\\vec{n_2} = 2\\vec{n_1}$, hai VTPT cùng phương nên hai mặt phẳng song song hoặc trùng.',
  },
  {
    content: 'Cho hình chóp $S.ABC$ có $SA \\perp (ABC)$, tam giác $ABC$ vuông tại $B$. $AB = 3, BC = 4, SA = 5$. Khoảng cách từ $A$ đến $(SBC)$ là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{15\\sqrt{34}}{34}$', B: '$\\dfrac{60}{\\sqrt{41}}$', C: '$3$', D: '$\\dfrac{15}{\\sqrt{34}}$' }),
    answer: 'A',
    explanation: '$V_{S.ABC} = \\dfrac{1}{3} \\cdot \\dfrac{1}{2} \\cdot 3 \\cdot 4 \\cdot 5 = 10$. $S_{\\triangle SBC}$: $SB = \\sqrt{9+25} = \\sqrt{34}$, $BC = 4$, $SC = \\sqrt{16+25} = \\sqrt{41}$. Dùng Heron hoặc tính trực tiếp. Vectơ $\\vec{SB} = (3, 0, -5)$ (nếu $S$ ở trên $A$), $\\vec{SC} = (3, 4, -5)$... Cách khác: $S_{SBC} = \\frac{1}{2}|\\vec{BC} \\times \\vec{BS}|$. Tính bằng toạ độ: $A(0,0,0)$, $B(3,0,0)$, $C(3,4,0)$, $S(0,0,5)$. $\\vec{BS} = (-3,0,5)$, $\\vec{BC} = (0,4,0)$. $\\vec{BS} \\times \\vec{BC} = (-20, 0, -12)$. $|\\ldots| = \\sqrt{400+144} = \\sqrt{544} = 4\\sqrt{34}$. $S_{SBC} = 2\\sqrt{34}$. $d(A, SBC) = \\frac{3V}{S_{SBC}} = \\frac{30}{2\\sqrt{34}} = \\frac{15}{\\sqrt{34}} = \\frac{15\\sqrt{34}}{34}$.',
  },
  {
    content: 'Điều kiện để hai đường thẳng trong không gian vuông góc là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: 'Tích vô hướng hai VTCP bằng $0$', B: 'Hai VTCP cùng phương', C: 'Hai đường thẳng cắt nhau', D: 'Hai đường thẳng song song' }),
    answer: 'A',
    explanation: 'Hai đường thẳng vuông góc khi $\\vec{u_1} \\cdot \\vec{u_2} = 0$.',
  },
  {
    content: 'Trong hình chóp đều $S.ABCD$ có tất cả các cạnh bằng $a$. Góc giữa cạnh bên và mặt đáy là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\arctan\\sqrt{2}$', B: '$45°$', C: '$60°$', D: '$\\arctan\\dfrac{\\sqrt{2}}{2}$' }),
    answer: 'D',
    explanation: 'Hình chiếu $S$ lên đáy là tâm $O$ của hình vuông. $AO = \\dfrac{a\\sqrt{2}}{2}$. $h = SO = \\sqrt{a^2 - \\dfrac{a^2}{2}} = \\dfrac{a}{\\sqrt{2}}$. $\\tan\\alpha = \\dfrac{h}{AO} = \\dfrac{a/\\sqrt{2}}{a\\sqrt{2}/2} = \\dfrac{1}{1} = 1 \\Rightarrow \\alpha = 45°$... Kiểm tra: $AO = a\\sqrt{2}/2$, $SA = a$, $h = \\sqrt{a^2 - a^2/2} = a/\\sqrt{2}$. $\\tan\\alpha = \\frac{a/\\sqrt{2}}{a\\sqrt{2}/2} = \\frac{a/\\sqrt{2}}{a\\sqrt{2}/2} = \\frac{1}{\\sqrt{2}} \\cdot \\frac{2}{\\sqrt{2}} = \\frac{2}{2} = 1$. Vậy $\\alpha = 45°$.',
  },
  {
    content: 'Cho hình lập phương $ABCD.A\'B\'C\'D\'$ cạnh $a$. Khoảng cách giữa hai đường thẳng $AC$ và $B\'D\'$ là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$a$', B: '$\\dfrac{a\\sqrt{2}}{2}$', C: '$\\dfrac{a}{2}$', D: '$a\\sqrt{2}$' }),
    answer: 'A',
    explanation: '$AC$ nằm trong $(ABCD)$, $B\'D\'$ nằm trong $(A\'B\'C\'D\')$. Hai mặt phẳng song song, cách nhau $a$. $AC \\parallel B\'D\'$ (cùng hướng đường chéo hình vuông). Vậy khoảng cách = khoảng cách giữa hai mp song song = $a$.',
  },
  {
    content: 'Cho tứ diện $ABCD$ có $AB \\perp CD$, $AC \\perp BD$. Khi đó:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$AD \\perp BC$', B: '$AD \\parallel BC$', C: '$AD = BC$', D: 'Không xác định được' }),
    answer: 'A',
    explanation: 'Nếu $\\vec{AB} \\cdot \\vec{CD} = 0$ và $\\vec{AC} \\cdot \\vec{BD} = 0$ thì $\\vec{AD} \\cdot \\vec{BC} = 0$. Chứng minh: $\\vec{AD} \\cdot \\vec{BC} = (\\vec{AC} + \\vec{CD}) \\cdot (\\vec{BA} + \\vec{AC}) = \\ldots$ Tính ra bằng $0$. Đây là tứ diện trực giao.',
  },
  {
    content: 'Cho hình chóp $S.ABC$ có $SA \\perp (ABC)$. Hình chiếu vuông góc của $S$ lên mặt phẳng $(ABC)$ là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: 'Điểm $A$', B: 'Trung điểm $BC$', C: 'Trọng tâm $\\triangle ABC$', D: 'Tâm đường tròn ngoại tiếp $\\triangle ABC$' }),
    answer: 'A',
    explanation: 'Vì $SA \\perp (ABC)$ nên hình chiếu vuông góc của $S$ lên $(ABC)$ chính là $A$.',
  },
  {
    content: 'Cho hình chóp tứ giác đều $S.ABCD$ cạnh đáy $a$, cạnh bên $a\\sqrt{2}$. Chiều cao của hình chóp là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$\\dfrac{a\\sqrt{6}}{2}$', B: '$a\\sqrt{2}$', C: '$a$', D: '$\\dfrac{a\\sqrt{2}}{2}$' }),
    answer: 'A',
    explanation: 'Nửa đường chéo đáy: $\\dfrac{a\\sqrt{2}}{2}$. $h = \\sqrt{(a\\sqrt{2})^2 - \\left(\\dfrac{a\\sqrt{2}}{2}\\right)^2} = \\sqrt{2a^2 - \\dfrac{a^2}{2}} = \\sqrt{\\dfrac{3a^2}{2}} = \\dfrac{a\\sqrt{6}}{2}$.',
  },
  {
    content: 'Trong hình hộp chữ nhật $ABCD.A\'B\'C\'D\'$ với $AB = 3, AD = 4, AA\' = 5$. Đường chéo $AG$ (với $G \\equiv C\'$) có độ dài:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$5\\sqrt{2}$', B: '$\\sqrt{50}$', C: '$10$', D: '$\\sqrt{34}$' }),
    answer: 'A',
    explanation: 'Đường chéo $= \\sqrt{3^2 + 4^2 + 5^2} = \\sqrt{50} = 5\\sqrt{2}$.',
  },
  {
    content: 'Góc giữa mặt phẳng $(SAB)$ và mặt phẳng đáy $(ABCD)$ trong hình chóp đều $S.ABCD$ cạnh $a$, chiều cao $h$, biết $h = \\dfrac{a}{2}$, là:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'ADVANCED',
    format: 'MULTIPLE_CHOICE',
    options: JSON.stringify({ A: '$45°$', B: '$30°$', C: '$60°$', D: '$\\arctan 2$' }),
    answer: 'A',
    explanation: 'Giao tuyến $(SAB) \\cap (ABCD)$ là $AB$. Kẻ $OM \\perp AB$ ($O$ là tâm đáy, $M$ là trung điểm $AB$). $OM = \\dfrac{a}{2}$. Góc $= \\arctan\\dfrac{h}{OM} = \\arctan\\dfrac{a/2}{a/2} = \\arctan 1 = 45°$.',
  },
  // --- TRUE_FALSE (3) ---
  {
    content: 'Cho hình chóp $S.ABCD$ có đáy $ABCD$ là hình chữ nhật. $SA \\perp (ABCD)$. Xét các phát biểu sau:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$SA \\perp AB$ (đúng, vì $SA \\perp (ABCD)$). $SA \\perp AD$ (đúng). $SA \\perp BD$ (đúng). $(SAB) \\perp (ABCD)$: đúng vì $SA \\perp (ABCD)$ và $SA \\subset (SAB)$. $(SAD) \\perp (SBC)$: cần kiểm tra... không nhất thiết đúng trong trường hợp tổng quát.',
    statementA: '$SA \\perp AB$',
    statementB: '$SA \\perp AD$',
    statementC: '$(SAB) \\perp (ABCD)$',
    statementD: '$(SAB) \\parallel (SCD)$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: false,
  },
  {
    content: 'Xét các phát biểu sau về quan hệ song song trong không gian:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: 'Hai đường thẳng song song với đường thẳng thứ ba → song song (đúng). Hai mp song song với mp thứ ba → song song (đúng). Đường thẳng song song mp thì song song mọi đường thẳng trong mp đó (sai, chỉ song song với giao tuyến). Hai đường thẳng không cắt nhau thì song song (sai, có thể chéo).',
    statementA: 'Hai đường thẳng cùng song song với đường thẳng thứ ba thì song song nhau',
    statementB: 'Hai mặt phẳng cùng song song với mặt phẳng thứ ba thì song song nhau',
    statementC: 'Đường thẳng song song mặt phẳng thì song song với mọi đường thẳng trong mặt phẳng đó',
    statementD: 'Hai đường thẳng không cắt nhau thì song song',
    answerA: true,
    answerB: true,
    answerC: false,
    answerD: false,
  },
  {
    content: 'Cho hình lập phương $ABCD.A\'B\'C\'D\'$. Xét các phát biểu sau:',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'TRUE_FALSE',
    options: '{}',
    answer: '',
    explanation: '$AC\' \\perp BD$: Kiểm tra — đúng (tính chất hình lập phương). $AB\' \\perp BC\'$: Kiểm tra bằng tích vô hướng — sai trong trường hợp tổng quát... Thực ra đúng. $A\'C \\perp B\'D$: đúng (đối xứng). Đường chéo $= a\\sqrt{3}$ (đúng). $AB \\parallel C\'D\'$ (đúng).',
    statementA: 'Đường chéo $AC\' = a\\sqrt{3}$',
    statementB: '$AB \\parallel C\'D\'$',
    statementC: '$AC\' \\perp B\'D$',
    statementD: '$(ABB\'A\') \\perp (BCC\'B\')$',
    answerA: true,
    answerB: true,
    answerC: true,
    answerD: true,
  },
  // --- SHORT_ANSWER (3) ---
  {
    content: 'Cho hình lập phương cạnh $a = 4$. Tính đường chéo.',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'RECOGNITION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '4√3',
    explanation: 'Đường chéo $= a\\sqrt{3} = 4\\sqrt{3}$.',
    correctAnswer: '4√3',
  },
  {
    content: 'Cho hình chóp $S.ABC$ có $SA \\perp (ABC)$, $SA = 6$, tam giác $ABC$ đều cạnh $4$. Tính thể tích.',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'COMPREHENSION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '8√3',
    explanation: '$S_{\\triangle ABC} = \\dfrac{4^2\\sqrt{3}}{4} = 4\\sqrt{3}$. $V = \\dfrac{1}{3} \\cdot 4\\sqrt{3} \\cdot 6 = 8\\sqrt{3}$.',
    correctAnswer: '8√3',
  },
  {
    content: 'Cho hình hộp chữ nhật $ABCD.A\'B\'C\'D\'$ với $AB = 1, AD = 2, AA\' = 2$. Tính khoảng cách giữa $AB$ và $C\'D\'$.',
    topic: 'SOLID_GEOMETRY',
    difficulty: 'APPLICATION',
    format: 'SHORT_ANSWER',
    options: '{}',
    answer: '2√2',
    explanation: '$AB \\parallel C\'D\'$. Khoảng cách giữa hai đường thẳng song song = khoảng cách từ $A$ đến $C\'D\'$. $A$ đến $D\'$: $AD\' = \\sqrt{AD^2 + AA\'^2} = \\sqrt{4+4} = 2\\sqrt{2}$. Mà $AD\' \\perp C\'D\'$ nên $d(A, C\'D\') = AD\' = 2\\sqrt{2}$.',
    correctAnswer: '2√2',
  },
];

// ============================================================
// Aggregate all questions
// ============================================================
const allQuestions: Q[] = [
  ...derivativesQuestions,
  ...integralsQuestions,
  ...functionsQuestions,
  ...limitsQuestions,
  ...complexNumbersQuestions,
  ...probabilityQuestions,
  ...sequencesQuestions,
  ...exponentialLogQuestions,
  ...volumeQuestions,
  ...analyticGeometryQuestions,
  ...solidGeometryQuestions,
];

async function main() {
  console.log(`\n=== Seed Questions v3 ===`);
  console.log(`Total questions to insert: ${allQuestions.length}\n`);

  const sql = neon(process.env.DATABASE_URL!);
  const now = new Date().toISOString();
  let created = 0;

  for (const q of allQuestions) {
    const id = randomUUID().replace(/-/g, '');
    await sql`
      INSERT INTO questions (id, content, topic, difficulty, format, options, answer, explanation, "questionType", "isActive", "createdAt", "updatedAt", "createdById",
        "statementA", "statementB", "statementC", "statementD",
        "answerA", "answerB", "answerC", "answerD", "correctAnswer")
      VALUES (
        ${id}, ${q.content}, ${q.topic}, ${q.difficulty}, ${q.format},
        ${q.options}::jsonb, ${q.answer}, ${q.explanation}, 'PRACTICE', true,
        ${now}::timestamp, ${now}::timestamp, ${TEACHER_ID},
        ${q.statementA ?? null}, ${q.statementB ?? null}, ${q.statementC ?? null}, ${q.statementD ?? null},
        ${q.answerA ?? null}, ${q.answerB ?? null}, ${q.answerC ?? null}, ${q.answerD ?? null},
        ${q.correctAnswer ?? null}
      )
    `;
    created++;
    if (created % 20 === 0) console.log(`  ...${created} questions created`);
  }

  console.log(`\nDone! Created ${created} questions.`);

  const summary = await sql`
    SELECT topic, count(*)::int as count 
    FROM questions 
    WHERE "createdById" = ${TEACHER_ID} 
    GROUP BY topic 
    ORDER BY topic
  `;
  console.log('\n=== Tổng câu hỏi theo chủ đề ===');
  console.table(summary);
}

main().catch(console.error);
