import { Topic, Difficulty, Prisma } from '@prisma/client';
import { MCQuestion, TFQuestion, SAQuestion } from './types';

export const complexNumbersQuestions: (MCQuestion | TFQuestion | SAQuestion)[] = [
  // RECOGNITION - MC (10)
  {
    content: 'Cho số phức $z = 3 + 4i$. Phần thực và phần ảo của $z$ lần lượt là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$3$ và $4$', B: '$4$ và $3$', C: '$3$ và $4i$', D: '$3i$ và $4$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: 'Số phức $z = a + bi$ có phần thực $a = 3$ và phần ảo $b = 4$ (không phải $4i$).',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: 'Mô-đun của số phức $z = 5 - 12i$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$13$', B: '$17$', C: '$7$', D: '$169$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$|z| = \\sqrt{25 + 144} = \\sqrt{169} = 13$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: 'Số phức liên hợp của $z = -2 + 7i$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$-2 - 7i$', B: '$2 - 7i$', C: '$2 + 7i$', D: '$-2 + 7i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$\\bar{z} = a - bi = -2 - 7i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: '$(3 + 2i) + (1 - 5i)$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$4 - 3i$', B: '$4 + 7i$', C: '$2 + 7i$', D: '$2 - 3i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$(3+1) + (2-5)i = 4 - 3i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: '$(6 + i) - (4 - 3i)$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$2 + 4i$', B: '$2 - 2i$', C: '$10 - 2i$', D: '$2 - 4i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$(6-4) + (1+3)i = 2 + 4i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: 'Số nào sau đây là số thuần ảo?',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$5i$', B: '$3 + 0i$', C: '$2 + i$', D: '$0$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: 'Số thuần ảo có phần thực $= 0$ và phần ảo $\\neq 0$. Chỉ $5i$ thoả mãn.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: 'Giá trị của $i^2$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$-1$', B: '$1$', C: '$i$', D: '$-i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: 'Theo định nghĩa đơn vị ảo: $i^2 = -1$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: 'Cho $z = 6i$. Mô-đun $|z|$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$6$', B: '$36$', C: '$0$', D: '$\\sqrt{6}$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$|z| = \\sqrt{0^2 + 6^2} = 6$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: 'Hai số phức $z_1 = a + bi$ và $z_2 = c + di$ bằng nhau khi và chỉ khi:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$a = c$ và $b = d$', B: '$a = d$ và $b = c$', C: '$a + b = c + d$', D: '$|z_1| = |z_2|$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: 'Hai số phức bằng nhau $\\Leftrightarrow$ phần thực bằng nhau và phần ảo bằng nhau.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  {
    content: 'Phần ảo của số phức $z = \\sqrt{2} - \\sqrt{3}\\,i$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$-\\sqrt{3}$', B: '$\\sqrt{3}$', C: '$-\\sqrt{3}\\,i$', D: '$\\sqrt{2}$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: 'Phần ảo là hệ số của $i$, tức $-\\sqrt{3}$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION,
  },
  // COMPREHENSION - MC (8)
  {
    content: 'Tích $(2 + 3i)(1 - 2i)$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$8 - i$', B: '$8 + i$', C: '$-4 - i$', D: '$2 - i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$2 - 4i + 3i - 6i^2 = 2 - i + 6 = 8 - i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  {
    content: 'Thương $\\dfrac{1 + i}{1 - i}$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$i$', B: '$-i$', C: '$1$', D: '$-1$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$\\dfrac{(1+i)^2}{(1-i)(1+i)} = \\dfrac{2i}{2} = i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  {
    content: 'Cho $z = 3 - 4i$. Tích $z \\cdot \\bar{z}$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$25$', B: '$-7$', C: '$7$', D: '$-25$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$z \\cdot \\bar{z} = |z|^2 = 9 + 16 = 25$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  {
    content: 'Giá trị của $i^{10}$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$-1$', B: '$1$', C: '$i$', D: '$-i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$i^{10} = i^{4 \\cdot 2 + 2} = i^2 = -1$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  {
    content: 'Dạng đại số của $\\dfrac{3 + 2i}{2 - i}$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$\\dfrac{4}{5} + \\dfrac{7}{5}i$', B: '$\\dfrac{4}{5} - \\dfrac{7}{5}i$', C: '$4 + 7i$', D: '$\\dfrac{8}{5} + \\dfrac{1}{5}i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$\\dfrac{(3+2i)(2+i)}{5} = \\dfrac{6+3i+4i-2}{5} = \\dfrac{4+7i}{5}$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  {
    content: 'Tích $(1 + 2i)(3 - i)$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$5 + 5i$', B: '$5 - 5i$', C: '$-1 + 5i$', D: '$1 + 5i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$3 - i + 6i - 2i^2 = 3 + 5i + 2 = 5 + 5i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  {
    content: 'Cho $z = a + bi$. Biểu thức $z + \\bar{z}$ bằng:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$2a$', B: '$2b$', C: '$2bi$', D: '$2ai$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$z + \\bar{z} = (a+bi) + (a-bi) = 2a$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  {
    content: 'Mô-đun của tích $(1 + i)(2 - 2i)$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$4$', B: '$2\\sqrt{2}$', C: '$8$', D: '$2$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$|1+i| = \\sqrt{2}$, $|2-2i| = 2\\sqrt{2}$. Tích mô-đun $= \\sqrt{2} \\cdot 2\\sqrt{2} = 4$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION,
  },
  // APPLICATION - MC (5)
  {
    content: 'Tìm số phức $z$ sao cho $z(1 + i) = 3 + i$.',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$2 - i$', B: '$2 + i$', C: '$1 - 2i$', D: '$1 + 2i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$z = \\dfrac{3+i}{1+i} = \\dfrac{(3+i)(1-i)}{2} = \\dfrac{4-2i}{2} = 2 - i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.APPLICATION,
  },
  {
    content: 'Phương trình $x^2 + 4 = 0$ có nghiệm là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$x = \\pm 2i$', B: '$x = \\pm 2$', C: '$x = \\pm 4i$', D: 'Vô nghiệm' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$x^2 = -4 \\Rightarrow x = \\pm 2i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.APPLICATION,
  },
  {
    content: 'Số phức $z$ thoả $z^2 = -2i$. Một nghiệm của phương trình là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$1 - i$', B: '$1 + i$', C: '$\\sqrt{2}i$', D: '$-1 + i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: 'Đặt $z = a+bi$: $a^2-b^2=0$, $2ab=-2$. Lấy $a=1, b=-1$: $(1-i)^2 = -2i$✓.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.APPLICATION,
  },
  {
    content: 'Số phức $z$ thoả $z - \\bar{z} = 6i$ và $z + \\bar{z} = 4$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$2 + 3i$', B: '$3 + 2i$', C: '$2 - 3i$', D: '$4 + 6i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$z + \\bar{z} = 2a = 4 \\Rightarrow a = 2$. $z - \\bar{z} = 2bi = 6i \\Rightarrow b = 3$. $z = 2 + 3i$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.APPLICATION,
  },
  {
    content: 'Tìm số phức $z = a + bi$ thoả $|z| = 5$ và $a = 2b$.',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: '$2\\sqrt{5} + \\sqrt{5}\\,i$', B: '$\\sqrt{5} + 2\\sqrt{5}\\,i$', C: '$4 + 2i$', D: '$2 + 4i$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$4b^2 + b^2 = 25 \\Rightarrow b = \\sqrt{5}$, $a = 2\\sqrt{5}$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.APPLICATION,
  },
  // ADVANCED - MC (2)
  {
    content: 'Tập hợp điểm $M(x,y)$ biểu diễn $z$ thoả $|z - 1| = |z + i|$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: 'Đường thẳng $y = -x$', B: 'Đường thẳng $y = x$', C: 'Đường tròn tâm $(1, -1)$', D: 'Đường thẳng $x + y = 1$' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$(x-1)^2+y^2 = x^2+(y+1)^2 \\Rightarrow -2x = 2y \\Rightarrow y = -x$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.ADVANCED,
  },
  {
    content: 'Cho $|z| = 1$. Tập hợp điểm biểu diễn $w = z + \\frac{1}{z}$ là:',
    format: 'MULTIPLE_CHOICE' as const,
    options: { A: 'Đoạn $[-2, 2]$ trên trục thực', B: 'Đường tròn đơn vị', C: 'Trục thực', D: 'Đoạn trên trục ảo' } as Prisma.JsonObject,
    answer: 'A' as const,
    explanation: '$z = \\cos\\theta + i\\sin\\theta$, $\\frac{1}{z} = \\bar{z}$. $w = 2\\cos\\theta \\in [-2, 2]$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.ADVANCED,
  },
  // RECOGNITION - TF (2)
  {
    content: 'Cho $z = 2 - 3i$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: 'Phần thực của $z$ là $2$.', answerA: true,
    statementB: '$\\bar{z} = 2 + 3i$.', answerB: true,
    statementC: '$|z|^2 = 13$.', answerC: true,
    statementD: '$z + \\bar{z} = -6i$.', answerD: false,
    explanation: '$|z|^2 = 4+9=13$✓. $z + \\bar{z} = (2-3i)+(2+3i) = 4 \\neq -6i$✗.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION, options: {} as Prisma.JsonObject, answer: '',
  },
  {
    content: 'Cho số phức $z = -1$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$z$ là số thực.', answerA: true,
    statementB: 'Phần ảo của $z$ bằng $0$.', answerB: true,
    statementC: '$|z| = 1$.', answerC: true,
    statementD: '$z$ là số thuần ảo.', answerD: false,
    explanation: '$z = -1 + 0i$: số thực✓. Phần ảo $= 0$✓. $|z|=1$✓. Thuần ảo cần phần thực $=0$ và phần ảo $\\neq 0$✗.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION, options: {} as Prisma.JsonObject, answer: '',
  },
  // COMPREHENSION - TF (2)
  {
    content: 'Cho $z_1 = 1 + 2i$, $z_2 = 3 - i$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$z_1 \\cdot z_2 = 5 + 5i$.', answerA: true,
    statementB: '$|z_1| = \\sqrt{5}$.', answerB: true,
    statementC: '$z_1 + z_2 = 4 + i$.', answerC: true,
    statementD: '$z_1 - z_2 = 4 - 3i$.', answerD: false,
    explanation: '$(1+2i)(3-i)=5+5i$✓. $|z_1|=\\sqrt{5}$✓. Tổng $=4+i$✓. Hiệu $=-2+3i \\neq 4-3i$✗.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION, options: {} as Prisma.JsonObject, answer: '',
  },
  {
    content: 'Cho $z = 2 + i$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$z \\cdot \\bar{z} = 5$.', answerA: true,
    statementB: '$z^2 = 3 + 4i$.', answerB: true,
    statementC: '$\\dfrac{1}{z} = \\dfrac{2-i}{5}$.', answerC: true,
    statementD: '$|z^2| = 4$.', answerD: false,
    explanation: '$|z|^2=5$✓. $(2+i)^2=3+4i$✓. $\\frac{1}{2+i}=\\frac{2-i}{5}$✓. $|z^2|=|z|^2=5 \\neq 4$✗.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION, options: {} as Prisma.JsonObject, answer: '',
  },
  // APPLICATION - TF (1)
  {
    content: 'Phương trình $z^2 - 2z + 5 = 0$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: 'Phương trình có hai nghiệm phức liên hợp nhau.', answerA: true,
    statementB: 'Hai nghiệm là $z = 1 + 2i$ và $z = 1 - 2i$.', answerB: true,
    statementC: 'Tích hai nghiệm bằng $5$.', answerC: true,
    statementD: 'Tổng hai nghiệm bằng $-2$.', answerD: false,
    explanation: '$\\Delta = 4-20=-16$. Nghiệm: $1\\pm 2i$✓. Tích $=5$✓. Tổng $=2 \\neq -2$✗.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.APPLICATION, options: {} as Prisma.JsonObject, answer: '',
  },
  // ADVANCED - TF (1)
  {
    content: 'Cho $z = x + yi$ thoả $|z - 2| = 2$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: 'Tập hợp điểm $M(x, y)$ là một đường tròn.', answerA: true,
    statementB: 'Đường tròn có tâm $I(2, 0)$.', answerB: true,
    statementC: 'Bán kính đường tròn bằng $2$.', answerC: true,
    statementD: 'Điểm $A(0, 0)$ nằm trên đường tròn.', answerD: true,
    explanation: '$(x-2)^2+y^2=4$: đường tròn tâm $(2;0)$, bán kính $2$✓✓✓. Tại $(0,0)$: $(0-2)^2+0=4$✓.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.ADVANCED, options: {} as Prisma.JsonObject, answer: '',
  },
  // RECOGNITION - SA (2)
  {
    content: 'Cho $z = 1 + i$. Tính $|z^2|$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '2', explanation: '$z^2 = 2i$. $|z^2| = 2$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION, options: {} as Prisma.JsonObject, answer: '2',
  },
  {
    content: 'Tính mô-đun của số phức $z = -6 + 8i$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '10', explanation: '$|z| = \\sqrt{36+64} = 10$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.RECOGNITION, options: {} as Prisma.JsonObject, answer: '10',
  },
  // COMPREHENSION - SA (1)
  {
    content: 'Tính phần thực của $\\dfrac{(1+i)^4}{2}$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '-2', explanation: '$(1+i)^2 = 2i$. $(1+i)^4 = -4$. $\\frac{-4}{2} = -2$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.COMPREHENSION, options: {} as Prisma.JsonObject, answer: '-2',
  },
  // APPLICATION - SA (1)
  {
    content: 'Tìm số nguyên dương $b$ nhỏ nhất để $(1 + bi)^2$ là số thuần ảo.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '1', explanation: '$(1+bi)^2 = 1-b^2+2bi$. Thuần ảo $\\Rightarrow 1-b^2=0 \\Rightarrow b=1$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.APPLICATION, options: {} as Prisma.JsonObject, answer: '1',
  },
  // ADVANCED - SA (1)
  {
    content: 'Cho $z = x + yi$ thoả $|z - i| = |z - 1|$. Biết $z = 3 + bi$. Tìm $b$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '3', explanation: '$M(x,y)$ nằm trên trung trực của $(0,1)$ và $(1,0)$: đường $y = x$. $z = 3+bi \\Rightarrow b = 3$.',
    topic: Topic.COMPLEX_NUMBERS, difficulty: Difficulty.ADVANCED, options: {} as Prisma.JsonObject, answer: '3',
  },
];
