import { Topic, Difficulty, Prisma } from '@prisma/client';
import { SeedQuestion } from './types';

export const sequencesQuestions: SeedQuestion[] = [
  // RECOGNITION - MC (10)
  {
    content: 'Cho cấp số cộng $(u_n)$ có $u_1 = 3$ và $d = 5$. Tìm $u_{10}$.',
    options: { A: '$48$', B: '$50$', C: '$45$', D: '$53$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_{10} = 3 + 9 \\cdot 5 = 48$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho cấp số nhân $(u_n)$ có $u_1 = 2$ và $q = 3$. Tìm $u_5$.',
    options: { A: '$162$', B: '$243$', C: '$486$', D: '$81$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_5 = 2 \\cdot 3^4 = 162$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Dãy số nào sau đây là cấp số cộng?',
    options: { A: '$1, 4, 7, 10, 13$', B: '$1, 2, 4, 8, 16$', C: '$1, 3, 6, 10, 15$', D: '$2, 5, 9, 14, 20$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: 'Dãy $1, 4, 7, 10, 13$ có hiệu liên tiếp không đổi bằng $3$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Dãy số nào sau đây là cấp số nhân?',
    options: { A: '$3, 6, 12, 24, 48$', B: '$3, 6, 9, 12, 15$', C: '$1, 2, 3, 5, 8$', D: '$2, 4, 8, 14, 22$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: 'Dãy $3, 6, 12, 24, 48$ có tỉ số liên tiếp không đổi bằng $2$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho cấp số cộng $(u_n)$ với $u_3 = 11$ và $u_7 = 23$. Tìm công sai $d$.',
    options: { A: '$3$', B: '$4$', C: '$2$', D: '$5$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_7 - u_3 = 4d \\Rightarrow 12 = 4d \\Rightarrow d = 3$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho cấp số nhân $(u_n)$ với $u_1 = 5$ và $u_4 = 40$. Tìm công bội $q$.',
    options: { A: '$2$', B: '$3$', C: '$4$', D: '$8$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$40 = 5q^3 \\Rightarrow q^3 = 8 \\Rightarrow q = 2$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho cấp số cộng $(u_n)$ có $u_1 = -2$ và $d = 4$. Tìm $u_{15}$.',
    options: { A: '$54$', B: '$56$', C: '$58$', D: '$52$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_{15} = -2 + 14 \\cdot 4 = 54$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho cấp số nhân $(u_n)$ có $u_1 = 1$ và $q = -2$. Tìm $u_6$.',
    options: { A: '$-32$', B: '$32$', C: '$-64$', D: '$64$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_6 = (-2)^5 = -32$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho dãy $(u_n)$ với $u_n = 3n - 1$. Dãy đó là:',
    options: { A: 'Cấp số cộng với $d = 3$', B: 'Cấp số cộng với $d = 1$', C: 'Cấp số nhân', D: 'Không phải CSC hay CSN' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_{n+1} - u_n = 3$, không đổi nên là CSC với $d = 3$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho CSC $(u_n)$ có $u_5 = 20$ và $u_1 = 4$. Tìm $d$.',
    options: { A: '$4$', B: '$3$', C: '$5$', D: '$2$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$20 = 4 + 4d \\Rightarrow d = 4$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, format: 'MULTIPLE_CHOICE' as const,
  },
  // RECOGNITION - TF (2)
  {
    content: 'Cho CSC $(u_n)$ có $u_1 = 2$, $d = 3$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$u_4 = 11$.', answerA: true,
    statementB: '$u_8 = 24$.', answerB: false,
    statementC: '$u_1 + u_2 + u_3 = 15$.', answerC: true,
    statementD: '$u_{20} = 60$.', answerD: false,
    explanation: '$u_4=11$✓. $u_8=23≠24$✗. Tổng $2+5+8=15$✓. $u_{20}=59≠60$✗.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, answer: '', options: {} as Prisma.JsonObject,
  },
  {
    content: 'Cho CSN $(u_n)$ có $u_1 = 3$, $q = 2$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$u_3 = 12$.', answerA: true,
    statementB: '$u_5 = 48$.', answerB: true,
    statementC: 'Dãy là dãy giảm.', answerC: false,
    statementD: '$u_1 \\cdot u_3 = u_2^2$.', answerD: true,
    explanation: '$u_3=12$✓. $u_5=48$✓. $q>0$ nên tăng✗. $3 \\cdot 12 = 36 = 6^2$✓.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, answer: '', options: {} as Prisma.JsonObject,
  },
  // RECOGNITION - SA (2)
  {
    content: 'Cho CSC $(u_n)$ có $u_1 = 7$, $d = -3$. Tính $u_8$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '-14', explanation: '$u_8 = 7 + 7(-3) = -14$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, options: {} as Prisma.JsonObject, answer: '-14',
  },
  {
    content: 'Cho CSN $(u_n)$ có $u_1 = 4$, $q = 3$. Tính $u_4$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '108', explanation: '$u_4 = 4 \\cdot 27 = 108$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.RECOGNITION, options: {} as Prisma.JsonObject, answer: '108',
  },
  // COMPREHENSION - MC (8)
  {
    content: 'Tính $S_{20}$ của CSC có $u_1 = 1$, $d = 2$.',
    options: { A: '$400$', B: '$380$', C: '$420$', D: '$390$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$S_{20} = \\frac{20}{2}(2 + 19 \\cdot 2) = 10 \\cdot 40 = 400$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Tính $S_6$ của CSN có $u_1 = 1$, $q = 2$.',
    options: { A: '$63$', B: '$64$', C: '$31$', D: '$32$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$S_6 = \\frac{2^6 - 1}{2 - 1} = 63$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Cho CSC $(u_n)$ có $S_n = 3n^2 + 2n$. Tìm $u_5$.',
    options: { A: '$29$', B: '$27$', C: '$31$', D: '$25$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_n = S_n - S_{n-1} = 6n - 1$, vậy $u_5 = 29$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'CSC $(u_n)$ có $u_1 = 5$, $u_{10} = 32$. Tính $S_{10}$.',
    options: { A: '$185$', B: '$175$', C: '$190$', D: '$170$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$S_{10} = \\frac{10}{2}(5 + 32) = 185$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Ba số $a, b, c$ theo thứ tự lập thành CSC, $a + b + c = 21$. Tìm $b$.',
    options: { A: '$7$', B: '$5$', C: '$9$', D: '$3$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: 'Vì CSC nên $a + c = 2b$, suy ra $3b = 21$, $b = 7$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'CSN $(u_n)$ có $u_2 = 6$, $u_5 = 162$. Tìm $u_1$.',
    options: { A: '$2$', B: '$3$', C: '$1$', D: '$6$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$q^3 = 162/6 = 27 \\Rightarrow q = 3$. $u_1 = 6/3 = 2$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'CSC $(u_n)$ có $u_3 + u_7 = 40$. Tìm $u_5$.',
    options: { A: '$20$', B: '$10$', C: '$15$', D: '$25$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: 'Tính chất CSC: $u_3 + u_7 = 2u_5 = 40 \\Rightarrow u_5 = 20$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Tổng vô hạn $S = 1 + \\frac{1}{2} + \\frac{1}{4} + \\frac{1}{8} + \\ldots$ bằng:',
    options: { A: '$2$', B: '$\\frac{3}{2}$', C: '$\\frac{5}{2}$', D: '$3$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: 'CSN lùi với $u_1 = 1$, $q = \\frac{1}{2}$. $S = \\frac{1}{1 - \\frac{1}{2}} = 2$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, format: 'MULTIPLE_CHOICE' as const,
  },
  // COMPREHENSION - TF (2)
  {
    content: 'CSC $(u_n)$ có $u_1 = 3$, $d = 4$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$S_5 = 55$.', answerA: true,
    statementB: '$u_1 + u_{10} = u_5 + u_6$.', answerB: true,
    statementC: '$S_{10} = 210$.', answerC: true,
    statementD: '$u_{10} = 40$.', answerD: false,
    explanation: '$S_5=55$✓. $u_1+u_{10}=u_5+u_6=42$✓. $S_{10}=210$✓. $u_{10}=39≠40$✗.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, answer: '', options: {} as Prisma.JsonObject,
  },
  {
    content: 'CSN $(u_n)$ có $u_1 = 2$, $q = -3$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$u_3 = 18$.', answerA: true,
    statementB: 'Dãy là dãy tăng.', answerB: false,
    statementC: '$S_4 = -40$.', answerC: true,
    statementD: '$u_2 \\cdot u_4 = u_3^2$.', answerD: true,
    explanation: '$u_3=18$✓. $q<0$ nên không tăng✗. $S_4=2\\cdot\\frac{1-81}{4}=-40$✓. $(-6)(-54)=324=18^2$✓.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, answer: '', options: {} as Prisma.JsonObject,
  },
  // COMPREHENSION - SA (1)
  {
    content: 'CSC $(u_n)$ có $u_1 = 2$, $d = 3$. Tính $S_{15}$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '345', explanation: '$S_{15} = \\frac{15}{2}(4 + 42) = 345$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.COMPREHENSION, options: {} as Prisma.JsonObject, answer: '345',
  },
  // APPLICATION - MC (5)
  {
    content: 'Một hội trường có $20$ hàng ghế. Hàng đầu có $15$ ghế, mỗi hàng sau thêm $2$ ghế. Tổng số ghế là:',
    options: { A: '$680$', B: '$700$', C: '$660$', D: '$720$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$S_{20} = \\frac{20}{2}(30 + 38) = 680$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.APPLICATION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Một quả bóng rơi từ độ cao $16$ m, mỗi lần nảy lên bằng $\\frac{3}{4}$ độ cao trước. Tổng quãng đường di chuyển là:',
    options: { A: '$112$ m', B: '$96$ m', C: '$128$ m', D: '$64$ m' } as Prisma.JsonObject,
    answer: 'A',
    explanation: 'Rơi: $\\frac{16}{1-3/4}=64$ m. Nảy: $\\frac{12}{1-3/4}=48$ m. Tổng $= 112$ m.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.APPLICATION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Doanh thu năm đầu $2$ tỷ, tăng $20\\%$/năm. Tổng $5$ năm xấp xỉ:',
    options: { A: '$14{,}88$ tỷ', B: '$12{,}44$ tỷ', C: '$10{,}00$ tỷ', D: '$16{,}50$ tỷ' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$S_5 = 2 \\cdot \\frac{1{,}2^5-1}{0{,}2} \\approx 14{,}88$ tỷ.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.APPLICATION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Quần thể vi khuẩn ban đầu $500$ con, mỗi giờ tăng gấp đôi. Sau $8$ giờ có bao nhiêu con?',
    options: { A: '$128000$', B: '$64000$', C: '$256000$', D: '$32000$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$500 \\cdot 2^8 = 128000$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.APPLICATION, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'Gửi tiết kiệm $10$ triệu, lãi suất $0{,}5\\%$/tháng (lãi kép). Sau $12$ tháng nhận được xấp xỉ:',
    options: { A: '$10{,}617$ triệu', B: '$10{,}500$ triệu', C: '$10{,}600$ triệu', D: '$11{,}000$ triệu' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$10 \\cdot 1{,}005^{12} \\approx 10{,}617$ triệu.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.APPLICATION, format: 'MULTIPLE_CHOICE' as const,
  },
  // APPLICATION - TF (1)
  {
    content: 'Vận động viên chạy ngày đầu $2$ km, mỗi ngày tăng thêm $0{,}5$ km. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: 'Ngày $10$ chạy $6{,}5$ km.', answerA: true,
    statementB: 'Tổng $10$ ngày đầu là $42{,}5$ km.', answerB: true,
    statementC: 'Ngày $20$ chạy $11{,}5$ km.', answerC: true,
    statementD: 'Tổng $7$ ngày đầu là $22{,}5$ km.', answerD: false,
    explanation: '$u_{10}=6{,}5$✓. $S_{10}=42{,}5$✓. $u_{20}=11{,}5$✓. $S_7=24{,}5≠22{,}5$✗.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.APPLICATION, answer: '', options: {} as Prisma.JsonObject,
  },
  // APPLICATION - SA (1)
  {
    content: 'Mỗi tháng gửi $5$ triệu (không lãi). Sau $24$ tháng tổng số tiền là bao nhiêu triệu?',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '120', explanation: '$5 \\times 24 = 120$ triệu.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.APPLICATION, options: {} as Prisma.JsonObject, answer: '120',
  },
  // ADVANCED - MC (2)
  {
    content: 'Dãy $(u_n)$: $u_1 = 1$, $u_{n+1} = 2u_n + 1$. Tìm $u_5$.',
    options: { A: '$31$', B: '$30$', C: '$32$', D: '$16$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$u_2=3, u_3=7, u_4=15, u_5=31$. Công thức: $u_n = 2^n - 1$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.ADVANCED, format: 'MULTIPLE_CHOICE' as const,
  },
  {
    content: 'CSC $(u_n)$ có $u_1 = a$, $d = 2a$, $S_{10} = 200$. Tìm $a$.',
    options: { A: '$2$', B: '$\\frac{20}{19}$', C: '$\\frac{10}{9}$', D: '$\\frac{20}{21}$' } as Prisma.JsonObject,
    answer: 'A',
    explanation: '$S_{10} = 5(2a + 18a) = 100a = 200 \\Rightarrow a = 2$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.ADVANCED, format: 'MULTIPLE_CHOICE' as const,
  },
  // ADVANCED - TF (1)
  {
    content: 'Dãy $(u_n)$: $u_1 = 2$, $u_{n+1} = \\frac{u_n}{2} + 1$. Xét tính đúng/sai:',
    format: 'TRUE_FALSE' as const,
    statementA: '$u_2 = 2$.', answerA: true,
    statementB: 'Dãy là dãy hằng $u_n = 2$.', answerB: true,
    statementC: '$\\lim_{n \\to \\infty} u_n = 3$.', answerC: false,
    statementD: '$u_3 = 2$.', answerD: true,
    explanation: '$u_2=2$✓. $u_n=2$ với mọi $n$✓. $\\lim u_n=2≠3$✗. $u_3=2$✓.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.ADVANCED, answer: '', options: {} as Prisma.JsonObject,
  },
  // ADVANCED - SA (1)
  {
    content: 'Dãy $(u_n)$: $u_1 = 3$, $u_{n+1} = 3u_n - 4$. Tính $u_4$.',
    format: 'SHORT_ANSWER' as const,
    correctAnswer: '29', explanation: '$u_2=5, u_3=11, u_4=29$.',
    topic: Topic.SEQUENCES, difficulty: Difficulty.ADVANCED, options: {} as Prisma.JsonObject, answer: '29',
  },
];
